/**
 * SwarmAI Unified Model Fleet
 * 92 NVIDIA NIM + 20 OpenRouter free = 112 models total
 *
 * RPM limits:
 *  NVIDIA free tier: 40 RPM most models, 20 RPM flagship (>200B), 60 RPM small (<8B)
 *  OpenRouter free: 20 RPM
 *
 * Total theoretical throughput: ~4,100 RPM across the fleet
 */

export type Provider = "nvidia" | "openrouter";

export interface UnifiedModel {
  id: string;
  name: string;
  provider: Provider;
  contextLength: number;
  domain: string;
  description: string;
  rateLimitRpm: number;
  parametersBillions?: number;
  isVision?: boolean;
  isCoder?: boolean;
  isReasoning?: boolean;
}

// ── NVIDIA NIM Models (92) ────────────────────────────────────────────────────
const NVIDIA_MODELS: UnifiedModel[] = [
  // Flagship / Ultra
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    name: "Nemotron 3 Ultra 550B",
    provider: "nvidia",
    contextLength: 1000000,
    domain: "general",
    description: "NVIDIA's largest MoE — 550B params, 1M context. Best for planning and reasoning.",
    rateLimitRpm: 20,
    parametersBillions: 550,
    isReasoning: true,
  },
  {
    id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    name: "Nemotron Ultra 253B",
    provider: "nvidia",
    contextLength: 128000,
    domain: "general",
    description: "NVIDIA fine-tuned Llama 253B with superior reasoning.",
    rateLimitRpm: 20,
    parametersBillions: 253,
    isReasoning: true,
  },
  {
    id: "nvidia/nemotron-4-340b-instruct",
    name: "Nemotron 4 340B",
    provider: "nvidia",
    contextLength: 4096,
    domain: "general",
    description: "NVIDIA's 340B flagship — exceptional at code and complex reasoning.",
    rateLimitRpm: 20,
    parametersBillions: 340,
  },
  {
    id: "qwen/qwen3.5-397b-a17b",
    name: "Qwen 3.5 397B MoE",
    provider: "nvidia",
    contextLength: 32768,
    domain: "general",
    description: "Qwen's 397B MoE flagship — top-tier across all domains.",
    rateLimitRpm: 20,
    parametersBillions: 397,
    isReasoning: true,
  },
  {
    id: "moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Moonshot AI's Kimi K2.6 — strong at long-context reasoning.",
    rateLimitRpm: 20,
    parametersBillions: 100,
  },
  {
    id: "mistralai/mistral-large-3-675b-instruct-2512",
    name: "Mistral Large 3 675B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Mistral's flagship 675B MoE — best-in-class generalist.",
    rateLimitRpm: 20,
    parametersBillions: 675,
  },
  {
    id: "minimaxai/minimax-m3",
    name: "MiniMax M3",
    provider: "nvidia",
    contextLength: 1000000,
    domain: "general",
    description: "MiniMax M3 — 1M context length, strong at long documents.",
    rateLimitRpm: 30,
    parametersBillions: 80,
  },
  // Large (70-100B)
  {
    id: "nvidia/llama-3.1-nemotron-70b-instruct",
    name: "Nemotron 70B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "NVIDIA fine-tuned Llama 70B with strong instruction following.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "nvidia/llama-3.3-nemotron-super-49b-v1",
    name: "Nemotron Super 49B v1",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "NVIDIA's Nemotron Super 49B — great for reasoning tasks.",
    rateLimitRpm: 30,
    parametersBillions: 49,
    isReasoning: true,
  },
  {
    id: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
    name: "Nemotron Super 49B v1.5",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "NVIDIA's Nemotron Super 49B v1.5 — improved version.",
    rateLimitRpm: 30,
    parametersBillions: 49,
    isReasoning: true,
  },
  {
    id: "nvidia/llama-3.1-nemotron-51b-instruct",
    name: "Nemotron 51B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "NVIDIA's 51B instruct model — efficient and capable.",
    rateLimitRpm: 30,
    parametersBillions: 51,
  },
  {
    id: "meta/llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Meta's flagship 70B — reliable across writing, analysis, and business tasks.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "meta/codellama-70b",
    name: "Code Llama 70B",
    provider: "nvidia",
    contextLength: 16384,
    domain: "code",
    description: "Meta's 70B specialized code model — deep code generation and analysis.",
    rateLimitRpm: 30,
    parametersBillions: 70,
    isCoder: true,
  },
  {
    id: "meta/llama-3.1-70b-instruct",
    name: "Llama 3.1 70B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Meta Llama 3.1 70B — strong all-around performer.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "abacusai/dracarys-llama-3.1-70b-instruct",
    name: "Dracarys 70B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "research",
    description: "AbacusAI's fine-tuned 70B — excellent at research and complex reasoning.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "nvidia/llama3-chatqa-1.5-70b",
    name: "ChatQA 1.5 70B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "research",
    description: "NVIDIA's 70B optimized for Q&A, RAG, and analytical tasks.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "writer/palmyra-fin-70b-32k",
    name: "Palmyra Finance 70B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "business",
    description: "Writer's 70B domain-specialized for financial analysis and business writing.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "writer/palmyra-med-70b",
    name: "Palmyra Medical 70B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "research",
    description: "Writer's 70B specialized for medical and scientific content.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "writer/palmyra-med-70b-32k",
    name: "Palmyra Medical 70B (32k)",
    provider: "nvidia",
    contextLength: 32768,
    domain: "research",
    description: "Writer's 70B medical model with extended context.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "meta/llama2-70b",
    name: "Llama 2 70B",
    provider: "nvidia",
    contextLength: 4096,
    domain: "general",
    description: "Meta Llama 2 70B — reliable general-purpose model.",
    rateLimitRpm: 40,
    parametersBillions: 70,
  },
  // Medium (20-50B)
  {
    id: "nvidia/nemotron-3-super-120b-a12b",
    name: "Nemotron 3 Super 120B",
    provider: "nvidia",
    contextLength: 1000000,
    domain: "general",
    description: "NVIDIA 120B MoE with 1M context — planning and architecture.",
    rateLimitRpm: 30,
    parametersBillions: 120,
  },
  {
    id: "mistralai/mistral-medium-3.5-128b",
    name: "Mistral Medium 3.5 128B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Mistral's 128B medium model — fast and highly capable.",
    rateLimitRpm: 30,
    parametersBillions: 128,
  },
  {
    id: "mistralai/mistral-small-4-119b-2603",
    name: "Mistral Small 4 119B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Mistral Small 4 — efficient 119B model for general tasks.",
    rateLimitRpm: 30,
    parametersBillions: 119,
  },
  {
    id: "qwen/qwen3.5-122b-a10b",
    name: "Qwen 3.5 122B MoE",
    provider: "nvidia",
    contextLength: 32768,
    domain: "general",
    description: "Qwen 3.5 122B MoE — strong reasoning and code.",
    rateLimitRpm: 30,
    parametersBillions: 122,
    isReasoning: true,
  },
  {
    id: "writer/palmyra-creative-122b",
    name: "Palmyra Creative 122B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "writing",
    description: "Writer's 122B model optimized for creative and long-form writing.",
    rateLimitRpm: 30,
    parametersBillions: 122,
  },
  {
    id: "mistralai/mistral-nemotron",
    name: "Mistral Nemotron",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "NVIDIA + Mistral collaboration model — strong instruct following.",
    rateLimitRpm: 30,
    parametersBillions: 70,
  },
  {
    id: "meta/llama-4-maverick-17b-128e-instruct",
    name: "Llama 4 Maverick 17B MoE",
    provider: "nvidia",
    contextLength: 1048576,
    domain: "general",
    description: "Meta Llama 4 Maverick — 17B active params / 400B total MoE, 1M context.",
    rateLimitRpm: 30,
    parametersBillions: 400,
    isReasoning: true,
  },
  {
    id: "mistralai/mistral-large",
    name: "Mistral Large",
    provider: "nvidia",
    contextLength: 32768,
    domain: "general",
    description: "Mistral Large — flagship reasoning model.",
    rateLimitRpm: 30,
    parametersBillions: 123,
  },
  {
    id: "mistralai/mistral-large-2-instruct",
    name: "Mistral Large 2 Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Mistral Large 2 — improved instruction following.",
    rateLimitRpm: 30,
    parametersBillions: 123,
  },
  {
    id: "mistralai/mixtral-8x22b-v0.1",
    name: "Mixtral 8x22B",
    provider: "nvidia",
    contextLength: 65536,
    domain: "general",
    description: "Mistral's MoE — 8 experts × 22B, great at data and analysis.",
    rateLimitRpm: 30,
    parametersBillions: 141,
  },
  {
    id: "databricks/dbrx-instruct",
    name: "DBRX Instruct",
    provider: "nvidia",
    contextLength: 32768,
    domain: "data",
    description: "Databricks' DBRX — specialized for data and analytics tasks.",
    rateLimitRpm: 30,
    parametersBillions: 132,
  },
  {
    id: "ai21labs/jamba-1.5-large-instruct",
    name: "Jamba 1.5 Large",
    provider: "nvidia",
    contextLength: 256000,
    domain: "research",
    description: "AI21's Jamba — SSM+Transformer hybrid with 256K context.",
    rateLimitRpm: 30,
    parametersBillions: 94,
  },
  {
    id: "deepseek-ai/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "DeepSeek V4 Pro — world-class reasoning and code.",
    rateLimitRpm: 20,
    parametersBillions: 685,
    isReasoning: true,
    isCoder: true,
  },
  {
    id: "deepseek-ai/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "DeepSeek V4 Flash — fast version, strong at code and writing.",
    rateLimitRpm: 30,
    parametersBillions: 20,
    isCoder: true,
  },
  {
    id: "minimaxai/minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "nvidia",
    contextLength: 1000000,
    domain: "general",
    description: "MiniMax M2.7 — ultra-long context, efficient MoE.",
    rateLimitRpm: 30,
    parametersBillions: 80,
  },
  // Code specialized
  {
    id: "ibm/granite-34b-code-instruct",
    name: "Granite 34B Code",
    provider: "nvidia",
    contextLength: 8192,
    domain: "code",
    description: "IBM's 34B code model — enterprise code generation and review.",
    rateLimitRpm: 30,
    parametersBillions: 34,
    isCoder: true,
  },
  {
    id: "mistralai/codestral-22b-instruct-v0.1",
    name: "Codestral 22B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "code",
    description: "Mistral's 22B code specialist — state-of-the-art code generation.",
    rateLimitRpm: 30,
    parametersBillions: 22,
    isCoder: true,
  },
  {
    id: "bigcode/starcoder2-15b",
    name: "StarCoder 2 15B",
    provider: "nvidia",
    contextLength: 16384,
    domain: "code",
    description: "BigCode's StarCoder2 15B — expert code assistant across 600+ languages.",
    rateLimitRpm: 40,
    parametersBillions: 15,
    isCoder: true,
  },
  // Medium-small (8-20B)
  {
    id: "bytedance/seed-oss-36b-instruct",
    name: "Seed OSS 36B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "ByteDance's Seed OSS 36B — fast and capable general model.",
    rateLimitRpm: 30,
    parametersBillions: 36,
  },
  {
    id: "mistralai/ministral-14b-instruct-2512",
    name: "Ministral 14B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Mistral's Ministral 14B — efficient for everyday tasks.",
    rateLimitRpm: 40,
    parametersBillions: 14,
  },
  {
    id: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
    name: "Mistral NeMo Minitron 8B",
    provider: "nvidia",
    contextLength: 8192,
    domain: "general",
    description: "NVIDIA's pruned Mistral NeMo — compact and efficient.",
    rateLimitRpm: 40,
    parametersBillions: 8,
  },
  {
    id: "nv-mistralai/mistral-nemo-12b-instruct",
    name: "Mistral NeMo 12B",
    provider: "nvidia",
    contextLength: 128000,
    domain: "general",
    description: "NVIDIA + Mistral NeMo 12B — great all-rounder.",
    rateLimitRpm: 40,
    parametersBillions: 12,
  },
  {
    id: "microsoft/phi-3.5-moe-instruct",
    name: "Phi-3.5 MoE",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Microsoft Phi-3.5 MoE — efficient small MoE with great instruction following.",
    rateLimitRpm: 40,
    parametersBillions: 42,
  },
  {
    id: "ibm/granite-3.0-8b-instruct",
    name: "Granite 3.0 8B",
    provider: "nvidia",
    contextLength: 8192,
    domain: "code",
    description: "IBM's enterprise 8B model — strong for DevOps and code tasks.",
    rateLimitRpm: 40,
    parametersBillions: 8,
    isCoder: true,
  },
  {
    id: "ibm/granite-8b-code-instruct",
    name: "Granite 8B Code",
    provider: "nvidia",
    contextLength: 4096,
    domain: "code",
    description: "IBM's 8B code specialist for enterprise code generation.",
    rateLimitRpm: 40,
    parametersBillions: 8,
    isCoder: true,
  },
  {
    id: "meta/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision",
    provider: "nvidia",
    contextLength: 131072,
    domain: "design",
    description: "Meta's multimodal 11B — vision + language for design tasks.",
    rateLimitRpm: 40,
    parametersBillions: 11,
    isVision: true,
  },
  {
    id: "meta/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Meta's compact 8B — fast for simple tasks.",
    rateLimitRpm: 60,
    parametersBillions: 8,
  },
  {
    id: "nvidia/llama-3.1-nemotron-nano-8b-v1",
    name: "Nemotron Nano 8B v1",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "NVIDIA's efficient Nano 8B model.",
    rateLimitRpm: 60,
    parametersBillions: 8,
  },
  {
    id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
    name: "Nemotron Nano Omni 30B Reasoning",
    provider: "nvidia",
    contextLength: 256000,
    domain: "reasoning",
    description: "Reasoning-optimized Nano model with 30B params.",
    rateLimitRpm: 40,
    parametersBillions: 30,
    isReasoning: true,
  },
  {
    id: "nvidia/nemotron-3-nano-30b-a3b",
    name: "Nemotron 3 Nano 30B",
    provider: "nvidia",
    contextLength: 256000,
    domain: "general",
    description: "NVIDIA's Nano 30B general model.",
    rateLimitRpm: 40,
    parametersBillions: 30,
  },
  {
    id: "nvidia/nemotron-nano-3-30b-a3b",
    name: "Nemotron Nano 3 30B",
    provider: "nvidia",
    contextLength: 256000,
    domain: "general",
    description: "NVIDIA Nemotron Nano 3 variant.",
    rateLimitRpm: 40,
    parametersBillions: 30,
  },
  {
    id: "nvidia/ising-calibration-1-35b-a3b",
    name: "Ising Calibration 35B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "data",
    description: "NVIDIA's Ising-based calibration model for data analysis.",
    rateLimitRpm: 40,
    parametersBillions: 35,
  },
  {
    id: "nvidia/cosmos-reason2-8b",
    name: "Cosmos Reason2 8B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "reasoning",
    description: "NVIDIA Cosmos reasoning model focused on structured thinking.",
    rateLimitRpm: 40,
    parametersBillions: 8,
    isReasoning: true,
  },
  {
    id: "z-ai/glm-5.2",
    name: "GLM 5.2",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "ZhipuAI GLM 5.2 — strong multilingual and writing model.",
    rateLimitRpm: 40,
    parametersBillions: 70,
  },
  {
    id: "01-ai/yi-large",
    name: "Yi Large",
    provider: "nvidia",
    contextLength: 32768,
    domain: "general",
    description: "01.AI Yi Large — strong multilingual capabilities.",
    rateLimitRpm: 40,
    parametersBillions: 34,
  },
  {
    id: "stepfun-ai/step-3.7-flash",
    name: "Step 3.7 Flash",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "StepFun Step 3.7 Flash — fast inference, strong reasoning.",
    rateLimitRpm: 40,
    parametersBillions: 100,
    isReasoning: true,
  },
  {
    id: "stepfun-ai/step-3.5-flash",
    name: "Step 3.5 Flash",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "StepFun Step 3.5 Flash — efficient and fast.",
    rateLimitRpm: 40,
    parametersBillions: 50,
  },
  {
    id: "mistralai/mixtral-8x7b-instruct-v0.1",
    name: "Mixtral 8x7B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "general",
    description: "Mistral's original MoE — fast and capable.",
    rateLimitRpm: 40,
    parametersBillions: 47,
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.3",
    name: "Mistral 7B Instruct v0.3",
    provider: "nvidia",
    contextLength: 32768,
    domain: "general",
    description: "Mistral 7B — fast and efficient for simple tasks.",
    rateLimitRpm: 60,
    parametersBillions: 7,
  },
  {
    id: "google/gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    provider: "nvidia",
    contextLength: 262144,
    domain: "general",
    description: "Google Gemma 4 31B — strong writing and design.",
    rateLimitRpm: 40,
    parametersBillions: 31,
  },
  {
    id: "google/diffusiongemma-26b-a4b-it",
    name: "DiffusionGemma 26B",
    provider: "nvidia",
    contextLength: 262144,
    domain: "general",
    description: "Google's diffusion-based Gemma model.",
    rateLimitRpm: 40,
    parametersBillions: 26,
  },
  {
    id: "google/gemma-3-12b-it",
    name: "Gemma 3 12B IT",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Google Gemma 3 12B — capable mid-size model.",
    rateLimitRpm: 40,
    parametersBillions: 12,
  },
  {
    id: "google/codegemma-1.1-7b",
    name: "CodeGemma 1.1 7B",
    provider: "nvidia",
    contextLength: 8192,
    domain: "code",
    description: "Google's code-specialized Gemma 7B — code completion and generation.",
    rateLimitRpm: 60,
    parametersBillions: 7,
    isCoder: true,
  },
  {
    id: "google/codegemma-7b",
    name: "CodeGemma 7B",
    provider: "nvidia",
    contextLength: 8192,
    domain: "code",
    description: "Google's CodeGemma 7B — code generation.",
    rateLimitRpm: 60,
    parametersBillions: 7,
    isCoder: true,
  },
  {
    id: "deepseek-ai/deepseek-coder-6.7b-instruct",
    name: "DeepSeek Coder 6.7B",
    provider: "nvidia",
    contextLength: 16384,
    domain: "code",
    description: "DeepSeek's code-specialized 6.7B — fast code tasks.",
    rateLimitRpm: 60,
    parametersBillions: 6.7,
    isCoder: true,
  },
  {
    id: "meta/llama-3.2-90b-vision-instruct",
    name: "Llama 3.2 90B Vision",
    provider: "nvidia",
    contextLength: 131072,
    domain: "design",
    description: "Meta's 90B vision model — best multimodal for design tasks.",
    rateLimitRpm: 20,
    parametersBillions: 90,
    isVision: true,
  },
  {
    id: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
    name: "Nemotron Nano VL 8B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "design",
    description: "NVIDIA's vision-language Nano 8B.",
    rateLimitRpm: 60,
    parametersBillions: 8,
    isVision: true,
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl",
    name: "Nemotron Nano 12B VL",
    provider: "nvidia",
    contextLength: 128000,
    domain: "design",
    description: "NVIDIA's 12B vision-language model.",
    rateLimitRpm: 40,
    parametersBillions: 12,
    isVision: true,
  },
  {
    id: "microsoft/phi-3-vision-128k-instruct",
    name: "Phi-3 Vision 128K",
    provider: "nvidia",
    contextLength: 128000,
    domain: "design",
    description: "Microsoft Phi-3 with vision — efficient multimodal.",
    rateLimitRpm: 40,
    parametersBillions: 14,
    isVision: true,
  },
  // Safety / Guard
  {
    id: "nvidia/llama-3.1-nemoguard-8b-content-safety",
    name: "NeMoGuard Content Safety 8B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "security",
    description: "NVIDIA's content safety classifier — NEMO Guard.",
    rateLimitRpm: 60,
    parametersBillions: 8,
  },
  {
    id: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
    name: "Nemotron Safety Guard 8B v3",
    provider: "nvidia",
    contextLength: 32768,
    domain: "security",
    description: "NVIDIA's safety guard model for filtering harmful content.",
    rateLimitRpm: 60,
    parametersBillions: 8,
  },
  {
    id: "nvidia/llama-3.1-nemoguard-8b-topic-control",
    name: "NeMoGuard Topic Control 8B",
    provider: "nvidia",
    contextLength: 32768,
    domain: "security",
    description: "NVIDIA's topic control model — constrains off-topic responses.",
    rateLimitRpm: 60,
    parametersBillions: 8,
  },
  {
    id: "meta/llama-guard-4-12b",
    name: "Llama Guard 4 12B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "security",
    description: "Meta's Llama Guard 4 — safety classification for AI systems.",
    rateLimitRpm: 60,
    parametersBillions: 12,
  },
  // Small / Fast
  {
    id: "ibm/granite-3.0-3b-a800m-instruct",
    name: "Granite 3.0 3B",
    provider: "nvidia",
    contextLength: 8192,
    domain: "code",
    description: "IBM's ultra-compact 3B for quick code and text tasks.",
    rateLimitRpm: 60,
    parametersBillions: 3,
    isCoder: true,
  },
  {
    id: "nvidia/nemotron-mini-4b-instruct",
    name: "Nemotron Mini 4B",
    provider: "nvidia",
    contextLength: 4096,
    domain: "general",
    description: "NVIDIA's 4B mini model — fast for simple tasks.",
    rateLimitRpm: 60,
    parametersBillions: 4,
  },
  {
    id: "nvidia/nvidia-nemotron-nano-9b-v2",
    name: "Nemotron Nano 9B v2",
    provider: "nvidia",
    contextLength: 128000,
    domain: "general",
    description: "NVIDIA's 9B nano model — efficient and capable.",
    rateLimitRpm: 60,
    parametersBillions: 9,
  },
  {
    id: "google/gemma-3-4b-it",
    name: "Gemma 3 4B IT",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Google Gemma 3 4B — lightweight instruction model.",
    rateLimitRpm: 60,
    parametersBillions: 4,
  },
  {
    id: "google/gemma-3n-e4b-it",
    name: "Gemma 3n E4B IT",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Google Gemma 3n nano variant — ultra-efficient.",
    rateLimitRpm: 60,
    parametersBillions: 4,
  },
  {
    id: "google/gemma-3n-e2b-it",
    name: "Gemma 3n E2B IT",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Google Gemma 3n 2B — fastest Gemma variant.",
    rateLimitRpm: 60,
    parametersBillions: 2,
  },
  {
    id: "google/gemma-2-2b-it",
    name: "Gemma 2 2B IT",
    provider: "nvidia",
    contextLength: 8192,
    domain: "general",
    description: "Google Gemma 2 2B — compact and capable.",
    rateLimitRpm: 60,
    parametersBillions: 2,
  },
  {
    id: "meta/llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Meta's 3B — ultra-fast for summaries and simple tasks.",
    rateLimitRpm: 60,
    parametersBillions: 3,
  },
  {
    id: "meta/llama-3.2-1b-instruct",
    name: "Llama 3.2 1B Instruct",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "Meta's 1B — lightest Llama model.",
    rateLimitRpm: 60,
    parametersBillions: 1,
  },
  {
    id: "aisingapore/sea-lion-7b-instruct",
    name: "SEA-LION 7B",
    provider: "nvidia",
    contextLength: 4096,
    domain: "general",
    description: "AI Singapore's Southeast Asian language model.",
    rateLimitRpm: 60,
    parametersBillions: 7,
  },
  {
    id: "sarvamai/sarvam-m",
    name: "Sarvam M",
    provider: "nvidia",
    contextLength: 32768,
    domain: "voice",
    description: "Sarvam AI's Indian language multilingual model.",
    rateLimitRpm: 60,
    parametersBillions: 7,
  },
  {
    id: "upstage/solar-10.7b-instruct",
    name: "Solar 10.7B",
    provider: "nvidia",
    contextLength: 4096,
    domain: "general",
    description: "Upstage Solar — efficient 10.7B general-purpose model.",
    rateLimitRpm: 60,
    parametersBillions: 10.7,
  },
  {
    id: "zyphra/zamba2-7b-instruct",
    name: "Zamba 2 7B",
    provider: "nvidia",
    contextLength: 4096,
    domain: "general",
    description: "Zyphra Zamba2 7B — SSM-based efficient model.",
    rateLimitRpm: 60,
    parametersBillions: 7,
  },
  {
    id: "openai/gpt-oss-120b",
    name: "OpenAI GPT OSS 120B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "OpenAI's open-source 120B model — highly capable.",
    rateLimitRpm: 30,
    parametersBillions: 120,
  },
  {
    id: "openai/gpt-oss-20b",
    name: "OpenAI GPT OSS 20B",
    provider: "nvidia",
    contextLength: 131072,
    domain: "general",
    description: "OpenAI's open-source 20B model — fast and capable.",
    rateLimitRpm: 40,
    parametersBillions: 20,
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct",
    name: "Qwen3 Next 80B Instruct",
    provider: "nvidia",
    contextLength: 262144,
    domain: "general",
    description: "Qwen3 80B instruction model — strong at research and data.",
    rateLimitRpm: 30,
    parametersBillions: 80,
  },
];

// ── OpenRouter Free Models (20) ───────────────────────────────────────────────
const OPENROUTER_MODELS: UnifiedModel[] = [
  {
    id: "qwen/qwen3-coder:free",
    name: "Qwen3 Coder 480B (OR)",
    provider: "openrouter",
    contextLength: 1048576,
    domain: "code",
    description: "Massive coding model with 1M context — best code generator on OpenRouter.",
    rateLimitRpm: 20,
    parametersBillions: 480,
    isCoder: true,
  },
  {
    id: "cohere/north-mini-code:free",
    name: "Cohere North Mini Code (OR)",
    provider: "openrouter",
    contextLength: 256000,
    domain: "code",
    description: "Cohere's dedicated code model.",
    rateLimitRpm: 20,
    isCoder: true,
  },
  {
    id: "poolside/laguna-m.1:free",
    name: "Poolside Laguna M.1 (OR)",
    provider: "openrouter",
    contextLength: 262144,
    domain: "code",
    description: "Poolside's medium coding model.",
    rateLimitRpm: 20,
    isCoder: true,
  },
  {
    id: "poolside/laguna-xs-2.1:free",
    name: "Poolside Laguna XS 2.1 (OR)",
    provider: "openrouter",
    contextLength: 262144,
    domain: "code",
    description: "Poolside's compact coding model.",
    rateLimitRpm: 20,
    isCoder: true,
  },
  {
    id: "nousresearch/hermes-3-llama-3.1-405b:free",
    name: "Hermes 3 405B (OR)",
    provider: "openrouter",
    contextLength: 131072,
    domain: "reasoning",
    description: "Nous Research 405B — best reasoning powerhouse on OpenRouter.",
    rateLimitRpm: 20,
    parametersBillions: 405,
    isReasoning: true,
  },
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b:free",
    name: "Nemotron Ultra 550B (OR)",
    provider: "openrouter",
    contextLength: 1000000,
    domain: "general",
    description: "NVIDIA 550B on OpenRouter — 1M context.",
    rateLimitRpm: 20,
    parametersBillions: 550,
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b:free",
    name: "Nemotron Super 120B (OR)",
    provider: "openrouter",
    contextLength: 1000000,
    domain: "general",
    description: "NVIDIA 120B on OpenRouter.",
    rateLimitRpm: 20,
    parametersBillions: 120,
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct:free",
    name: "Qwen3 Next 80B (OR)",
    provider: "openrouter",
    contextLength: 262144,
    domain: "general",
    description: "Qwen3 80B on OpenRouter.",
    rateLimitRpm: 20,
    parametersBillions: 80,
  },
  {
    id: "meta/llama-3.3-70b-instruct:free",
    name: "Llama 3.3 70B (OR)",
    provider: "openrouter",
    contextLength: 131072,
    domain: "general",
    description: "Meta's 70B on OpenRouter — reliable for writing and business.",
    rateLimitRpm: 20,
    parametersBillions: 70,
  },
  {
    id: "google/gemma-4-31b-it:free",
    name: "Gemma 4 31B (OR)",
    provider: "openrouter",
    contextLength: 262144,
    domain: "general",
    description: "Google Gemma 4 31B on OpenRouter.",
    rateLimitRpm: 20,
    parametersBillions: 31,
  },
  {
    id: "google/gemma-4-26b-a4b-it:free",
    name: "Gemma 4 26B (OR)",
    provider: "openrouter",
    contextLength: 262144,
    domain: "general",
    description: "Google Gemma 4 26B sparse on OpenRouter.",
    rateLimitRpm: 20,
    parametersBillions: 26,
  },
  {
    id: "tencent/hy3:free",
    name: "Tencent Hy3 (OR)",
    provider: "openrouter",
    contextLength: 262144,
    domain: "general",
    description: "Tencent Hy3 on OpenRouter.",
    rateLimitRpm: 20,
  },
  {
    id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    name: "Nemotron Nano Omni Reasoning (OR)",
    provider: "openrouter",
    contextLength: 256000,
    domain: "reasoning",
    description: "NVIDIA reasoning Nano on OpenRouter.",
    rateLimitRpm: 20,
    isReasoning: true,
  },
  {
    id: "openai/gpt-oss-20b:free",
    name: "GPT OSS 20B (OR)",
    provider: "openrouter",
    contextLength: 131072,
    domain: "general",
    description: "OpenAI OSS 20B on OpenRouter.",
    rateLimitRpm: 20,
  },
  {
    id: "nvidia/nemotron-3-nano-30b-a3b:free",
    name: "Nemotron Nano 30B (OR)",
    provider: "openrouter",
    contextLength: 256000,
    domain: "general",
    description: "NVIDIA Nano 30B on OpenRouter.",
    rateLimitRpm: 20,
  },
  {
    id: "nvidia/nemotron-nano-9b-v2:free",
    name: "Nemotron 9B v2 (OR)",
    provider: "openrouter",
    contextLength: 128000,
    domain: "general",
    description: "NVIDIA 9B on OpenRouter — fast.",
    rateLimitRpm: 20,
  },
  {
    id: "meta/llama-3.2-3b-instruct:free",
    name: "Llama 3.2 3B (OR)",
    provider: "openrouter",
    contextLength: 131072,
    domain: "general",
    description: "Llama 3.2 3B on OpenRouter — ultra-fast.",
    rateLimitRpm: 20,
  },
  {
    id: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    name: "Dolphin Mistral 24B (OR)",
    provider: "openrouter",
    contextLength: 32768,
    domain: "writing",
    description: "Dolphin Mistral creative model on OpenRouter.",
    rateLimitRpm: 20,
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl:free",
    name: "Nemotron Nano 12B VL (OR)",
    provider: "openrouter",
    contextLength: 128000,
    domain: "design",
    description: "NVIDIA vision-language 12B on OpenRouter.",
    rateLimitRpm: 20,
    isVision: true,
  },
  {
    id: "nvidia/nemotron-3.5-content-safety:free",
    name: "Nemotron Content Safety (OR)",
    provider: "openrouter",
    contextLength: 128000,
    domain: "security",
    description: "NVIDIA content safety on OpenRouter.",
    rateLimitRpm: 20,
  },
];

// ── Deduplicated unified fleet ─────────────────────────────────────────────────
const seen = new Set<string>();
export const ALL_MODELS: UnifiedModel[] = [
  ...NVIDIA_MODELS,
  ...OPENROUTER_MODELS,
].filter((m) => {
  if (seen.has(m.id)) return false;
  seen.add(m.id);
  return true;
});

export const MODELS = ALL_MODELS; // backwards compat

// ── Legacy OpenRouter-only list (for backwards compat) ─────────────────────────
export const MODEL_IDS = {
  CODER_LARGE: "qwen/qwen3-coder:free",
  CODER_MEDIUM: "cohere/north-mini-code:free",
  CODER_POOLSIDE_M: "poolside/laguna-m.1:free",
  CODER_POOLSIDE_XS: "poolside/laguna-xs-2.1:free",
  REASONING_LARGE: "nousresearch/hermes-3-llama-3.1-405b:free",
  GENERAL_ULTRA: "nvidia/nemotron-3-ultra-550b-a55b:free",
  GENERAL_SUPER: "nvidia/nemotron-3-super-120b-a12b:free",
  GENERAL_QWEN: "qwen/qwen3-next-80b-a3b-instruct:free",
  GENERAL_LLAMA: "meta/llama-3.3-70b-instruct:free",
  GENERAL_GEMMA31: "google/gemma-4-31b-it:free",
  GENERAL_GEMMA26: "google/gemma-4-26b-a4b-it:free",
  GENERAL_TENCENT: "tencent/hy3:free",
  REASONING_NANO: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
  GENERAL_GPT_OSS: "openai/gpt-oss-20b:free",
  GENERAL_NANO30: "nvidia/nemotron-3-nano-30b-a3b:free",
  FAST_9B: "nvidia/nemotron-nano-9b-v2:free",
  FAST_3B: "meta/llama-3.2-3b-instruct:free",
  CREATIVE: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
  VISION: "nvidia/nemotron-nano-12b-v2-vl:free",
  SAFETY: "nvidia/nemotron-3.5-content-safety:free",
} as const;

/** Quick lookup */
export function getModelById(id: string): UnifiedModel | undefined {
  return ALL_MODELS.find((m) => m.id === id);
}
