import { MODEL_IDS } from "../models/registry.js";

export interface AgentDefinition {
  id: string;
  name: string;
  domain: string;
  subdomain: string;
  description: string;
  systemPrompt: string;
  preferredModel: string;
  capabilities: string[];
  priority: number;
}

function a(
  id: string,
  name: string,
  domain: string,
  subdomain: string,
  description: string,
  model: string,
  capabilities: string[],
  priority = 5,
): AgentDefinition {
  return {
    id,
    name,
    domain,
    subdomain,
    description,
    systemPrompt: `You are ${name}. ${description}\n\nYour role: Analyze the given task and provide your specialized output. Be thorough, precise, and actionable. Format your response clearly with sections as needed. Focus exclusively on your domain of expertise.`,
    preferredModel: model,
    capabilities,
    priority,
  };
}

const M = MODEL_IDS;

export const AGENT_REGISTRY: AgentDefinition[] = [
  // ── CODE DOMAIN (60 agents) ──────────────────────────────────────────────
  a("code-js-frontend", "JavaScript Frontend Developer", "code", "javascript", "Expert in modern JavaScript frontend development with React, Vue, and vanilla JS.", M.CODER_LARGE, ["react", "vue", "typescript", "webpack", "vite"], 9),
  a("code-ts-specialist", "TypeScript Architect", "code", "typescript", "Deep TypeScript expertise including generics, decorators, and advanced type patterns.", M.CODER_LARGE, ["typescript", "type-safety", "interfaces", "generics", "decorators"], 9),
  a("code-react-expert", "React Specialist", "code", "react", "Expert in React hooks, context, performance optimization, and component architecture.", M.CODER_LARGE, ["react", "hooks", "context", "memoization", "suspense"], 9),
  a("code-nextjs", "Next.js Developer", "code", "nextjs", "Specialist in Next.js App Router, SSR, ISR, and full-stack Next.js applications.", M.CODER_LARGE, ["nextjs", "ssr", "isr", "app-router", "vercel"], 8),
  a("code-nodejs-backend", "Node.js Backend Developer", "code", "nodejs", "Expert in Node.js backend development with Express, Fastify, and Hapi.", M.CODER_MEDIUM, ["nodejs", "express", "fastapi", "rest-api", "middleware"], 9),
  a("code-python-general", "Python Developer", "code", "python", "General Python developer covering scripts, automation, and application code.", M.CODER_MEDIUM, ["python", "pip", "scripting", "automation", "pydantic"], 9),
  a("code-python-fastapi", "FastAPI Developer", "code", "python-web", "Expert in FastAPI, Pydantic v2, async Python, and modern Python APIs.", M.CODER_MEDIUM, ["fastapi", "pydantic", "async", "uvicorn", "sqlalchemy"], 8),
  a("code-python-django", "Django Developer", "code", "python-web", "Django expert covering ORM, views, middleware, and Django REST Framework.", M.CODER_MEDIUM, ["django", "drf", "orm", "migrations", "celery"], 8),
  a("code-python-data", "Python Data Engineer", "code", "python-data", "Python specialist for data pipelines, pandas, numpy, and data processing.", M.CODER_LARGE, ["pandas", "numpy", "polars", "data-pipeline", "etl"], 8),
  a("code-go-services", "Go Microservices Developer", "code", "go", "Expert in Go microservices, goroutines, channels, and high-performance APIs.", M.CODER_POOLSIDE_M, ["golang", "goroutines", "grpc", "microservices", "concurrency"], 8),
  a("code-go-cli", "Go CLI Developer", "code", "go", "Specialist in building CLI tools with Go, cobra, and viper.", M.CODER_POOLSIDE_M, ["golang", "cobra", "cli", "viper", "cross-platform"], 7),
  a("code-rust-systems", "Rust Systems Programmer", "code", "rust", "Expert in Rust systems programming, ownership model, and zero-cost abstractions.", M.CODER_POOLSIDE_M, ["rust", "ownership", "traits", "async-rust", "cargo"], 8),
  a("code-rust-wasm", "Rust/WASM Developer", "code", "rust", "Specialist in Rust compiled to WebAssembly for browser and edge environments.", M.CODER_POOLSIDE_M, ["rust", "wasm", "wasm-bindgen", "webassembly", "edge"], 7),
  a("code-java-spring", "Java Spring Boot Developer", "code", "java", "Enterprise Java developer with Spring Boot, Spring Security, and JPA expertise.", M.CODER_MEDIUM, ["java", "spring-boot", "jpa", "maven", "microservices"], 8),
  a("code-java-android", "Android Developer (Java)", "code", "android", "Android development with Java, Jetpack components, and Material Design.", M.CODER_MEDIUM, ["android", "java", "jetpack", "material-design", "gradle"], 7),
  a("code-kotlin-android", "Android Developer (Kotlin)", "code", "kotlin", "Modern Android development with Kotlin, Compose, and Coroutines.", M.CODER_MEDIUM, ["kotlin", "compose", "coroutines", "android", "viewmodel"], 8),
  a("code-swift-ios", "iOS Developer (Swift)", "code", "swift", "iOS development with Swift, SwiftUI, Combine, and UIKit.", M.CODER_MEDIUM, ["swift", "swiftui", "combine", "uikit", "xcode"], 8),
  a("code-cpp-systems", "C++ Systems Developer", "code", "cpp", "Expert in modern C++ (17/20), templates, RAII, and performance optimization.", M.CODER_POOLSIDE_M, ["cpp", "templates", "raii", "stl", "cmake"], 7),
  a("code-c-embedded", "C Embedded Developer", "code", "c", "Embedded C development for microcontrollers, RTOS, and low-level hardware.", M.CODER_POOLSIDE_M, ["c", "embedded", "rtos", "drivers", "microcontrollers"], 7),
  a("code-php-laravel", "Laravel PHP Developer", "code", "php", "Laravel expert covering Eloquent ORM, queues, broadcasting, and Livewire.", M.CODER_MEDIUM, ["php", "laravel", "eloquent", "livewire", "composer"], 7),
  a("code-ruby-rails", "Ruby on Rails Developer", "code", "ruby", "Ruby on Rails developer with ActiveRecord, ActionCable, and Hotwire expertise.", M.CODER_MEDIUM, ["ruby", "rails", "activerecord", "hotwire", "rubygems"], 7),
  a("code-scala-fp", "Scala Functional Developer", "code", "scala", "Functional programming in Scala with Cats, ZIO, and Akka.", M.CODER_MEDIUM, ["scala", "cats", "zio", "akka", "functional-programming"], 6),
  a("code-sql-postgres", "PostgreSQL Expert", "code", "sql", "PostgreSQL specialist for complex queries, indexing, CTEs, and performance tuning.", M.CODER_LARGE, ["postgresql", "sql", "indexes", "query-optimization", "cte"], 9),
  a("code-sql-schema", "Database Schema Designer", "code", "sql", "Expert in relational schema design, normalization, and data modeling.", M.CODER_MEDIUM, ["schema-design", "normalization", "erd", "migrations", "constraints"], 8),
  a("code-nosql", "NoSQL Developer", "code", "nosql", "Expert in MongoDB, Redis, DynamoDB, and Cassandra data modeling.", M.CODER_MEDIUM, ["mongodb", "redis", "dynamodb", "cassandra", "nosql"], 7),
  a("code-graphql", "GraphQL Developer", "code", "graphql", "GraphQL schema design, resolvers, subscriptions, and federation.", M.CODER_LARGE, ["graphql", "apollo", "schema", "resolvers", "federation"], 8),
  a("code-api-design", "REST API Designer", "code", "api", "Expert REST API design following OpenAPI spec, versioning, and best practices.", M.CODER_MEDIUM, ["rest", "openapi", "versioning", "pagination", "hateoas"], 8),
  a("code-grpc", "gRPC Developer", "code", "grpc", "Protocol Buffers, gRPC services, streaming, and service mesh patterns.", M.CODER_POOLSIDE_M, ["grpc", "protobuf", "streaming", "service-mesh", "tls"], 7),
  a("code-shell-bash", "Shell/Bash Scripter", "code", "shell", "Expert in Bash scripting, shell automation, cron jobs, and Unix tools.", M.CODER_MEDIUM, ["bash", "shell", "automation", "cron", "unix"], 7),
  a("code-iac-terraform", "Terraform Developer", "code", "iac", "Infrastructure as Code with Terraform, modules, state management, and providers.", M.CODER_POOLSIDE_M, ["terraform", "iac", "modules", "state", "providers"], 8),
  a("code-iac-pulumi", "Pulumi Developer", "code", "iac", "Pulumi IaC using TypeScript/Python for cloud resource management.", M.CODER_POOLSIDE_M, ["pulumi", "iac", "cloud", "typescript", "stacks"], 7),
  a("code-review", "Code Reviewer", "code", "review", "Expert code reviewer identifying bugs, antipatterns, security issues, and improvements.", M.REASONING_LARGE, ["code-review", "static-analysis", "best-practices", "security", "refactoring"], 9),
  a("code-performance", "Performance Optimizer", "code", "optimization", "Specialist in profiling, bottleneck identification, and performance optimization.", M.CODER_LARGE, ["profiling", "optimization", "caching", "concurrency", "benchmarking"], 8),
  a("code-refactoring", "Refactoring Specialist", "code", "refactoring", "Expert in code refactoring, design patterns, and technical debt reduction.", M.REASONING_LARGE, ["refactoring", "design-patterns", "solid", "dry", "clean-code"], 8),
  a("code-mobile-rn", "React Native Developer", "code", "mobile", "Cross-platform mobile development with React Native and Expo.", M.CODER_LARGE, ["react-native", "expo", "mobile", "navigation", "native-modules"], 8),
  a("code-flutter", "Flutter Developer", "code", "mobile", "Flutter and Dart development for iOS and Android apps.", M.CODER_MEDIUM, ["flutter", "dart", "widgets", "state-management", "pub"], 7),
  a("code-wasm", "WebAssembly Developer", "code", "wasm", "WebAssembly modules, memory management, and JS-WASM interop.", M.CODER_POOLSIDE_M, ["wasm", "webassembly", "emscripten", "memory", "simd"], 7),
  a("code-elixir", "Elixir/Phoenix Developer", "code", "elixir", "Functional Elixir with Phoenix, LiveView, OTP, and GenServers.", M.CODER_MEDIUM, ["elixir", "phoenix", "liveview", "otp", "genserver"], 7),
  a("code-svelte", "Svelte Developer", "code", "svelte", "SvelteKit developer with stores, transitions, and server-side rendering.", M.CODER_LARGE, ["svelte", "sveltekit", "stores", "transitions", "ssr"], 7),
  a("code-solidity", "Solidity Smart Contract Developer", "code", "blockchain", "Ethereum smart contracts with Solidity, Hardhat, and OpenZeppelin.", M.CODER_POOLSIDE_M, ["solidity", "ethereum", "smart-contracts", "hardhat", "openzeppelin"], 7),
  a("code-test-writer", "Test Suite Writer", "code", "testing", "Writes comprehensive unit and integration test suites for any codebase.", M.CODER_LARGE, ["testing", "jest", "vitest", "pytest", "test-coverage"], 8),
  a("code-doc-generator", "Code Documentation Generator", "code", "documentation", "Generates JSDoc, docstrings, README files, and API documentation.", M.GENERAL_LLAMA, ["documentation", "jsdoc", "docstrings", "readme", "api-docs"], 7),
  a("code-migrate", "Migration Specialist", "code", "migration", "Expert in codebase migrations between frameworks, languages, and versions.", M.REASONING_LARGE, ["migration", "upgrade", "compatibility", "breaking-changes", "codemods"], 7),
  a("code-microservices", "Microservices Architect", "code", "architecture", "Microservices patterns, service decomposition, and distributed system design.", M.GENERAL_SUPER, ["microservices", "domain-driven-design", "api-gateway", "service-mesh", "saga"], 8),
  a("code-event-driven", "Event-Driven Systems Developer", "code", "architecture", "Event sourcing, CQRS, message queues (Kafka, RabbitMQ), and event-driven patterns.", M.GENERAL_SUPER, ["event-sourcing", "cqrs", "kafka", "rabbitmq", "event-driven"], 8),
  a("code-websockets", "WebSocket Developer", "code", "realtime", "Real-time applications with WebSockets, Socket.io, and SSE.", M.CODER_LARGE, ["websockets", "socketio", "sse", "realtime", "pubsub"], 8),
  a("code-pwa", "Progressive Web App Developer", "code", "web", "PWA development with service workers, manifest, offline support, and push notifications.", M.CODER_LARGE, ["pwa", "service-workers", "offline", "push-notifications", "manifest"], 7),
  a("code-accessibility", "Accessibility (A11y) Developer", "code", "accessibility", "Web accessibility specialist: WCAG 2.1, ARIA, keyboard navigation, and screen readers.", M.CODER_MEDIUM, ["a11y", "wcag", "aria", "keyboard-navigation", "screen-readers"], 8),
  a("code-css-expert", "CSS/Styling Expert", "code", "css", "Advanced CSS: animations, custom properties, grid, flexbox, and Tailwind.", M.CODER_LARGE, ["css", "animations", "tailwind", "design-tokens", "responsive"], 7),
  a("code-state-management", "State Management Expert", "code", "state", "Redux, Zustand, Jotai, MobX, and state machine patterns.", M.CODER_LARGE, ["redux", "zustand", "jotai", "xstate", "state-machines"], 7),
  a("code-auth", "Authentication Implementer", "code", "auth", "Implements authentication: JWT, OAuth2, PKCE, session management, and MFA.", M.CODER_MEDIUM, ["auth", "jwt", "oauth2", "sessions", "mfa"], 8),
  a("code-payments", "Payment Integration Developer", "code", "payments", "Stripe, PayPal, and payment gateway integration with webhooks and reconciliation.", M.CODER_MEDIUM, ["stripe", "payments", "webhooks", "subscriptions", "pci"], 7),
  a("code-search", "Search Implementation Expert", "code", "search", "Full-text search with Elasticsearch, Typesense, Meilisearch, and PostgreSQL FTS.", M.CODER_LARGE, ["elasticsearch", "typesense", "full-text-search", "relevance", "indexing"], 7),
  a("code-caching", "Caching Architect", "code", "caching", "Redis caching strategies, CDN configuration, browser caching, and cache invalidation.", M.CODER_MEDIUM, ["redis", "caching", "cdn", "ttl", "cache-invalidation"], 7),
  a("code-queue", "Job Queue Developer", "code", "queues", "Background job processing with BullMQ, Celery, Sidekiq, and workflow orchestration.", M.CODER_MEDIUM, ["bullmq", "celery", "sidekiq", "workers", "job-queues"], 7),
  a("code-monorepo", "Monorepo Architect", "code", "tooling", "Turborepo, Nx, pnpm workspaces, and monorepo CI/CD strategies.", M.CODER_MEDIUM, ["turborepo", "nx", "monorepo", "pnpm-workspaces", "build-systems"], 7),
  a("code-bundler", "Build Tools Expert", "code", "tooling", "Webpack, Vite, Rollup, esbuild configuration and optimization.", M.CODER_MEDIUM, ["webpack", "vite", "rollup", "esbuild", "bundling"], 7),
  a("code-regex", "Regex & Text Processing Expert", "code", "utilities", "Complex regular expressions, text parsing, and string manipulation.", M.CODER_MEDIUM, ["regex", "text-parsing", "pattern-matching", "string-manipulation", "nlp-basic"], 6),
  a("code-encryption", "Cryptography Developer", "code", "security", "AES, RSA, ECDSA, hashing, and cryptographic protocol implementation.", M.CODER_MEDIUM, ["cryptography", "aes", "rsa", "hashing", "tls"], 7),

  // ── RESEARCH DOMAIN (35 agents) ─────────────────────────────────────────
  a("research-web", "Web Research Analyst", "research", "web", "Comprehensive web research, source evaluation, and information synthesis.", M.REASONING_LARGE, ["web-research", "source-evaluation", "synthesis", "citations", "fact-finding"], 9),
  a("research-academic", "Academic Paper Analyst", "research", "academic", "Analyzes academic papers, extracts methodologies, findings, and limitations.", M.GENERAL_ULTRA, ["academic", "papers", "methodology", "findings", "literature-review"], 8),
  a("research-market", "Market Research Analyst", "research", "market", "Market sizing, TAM/SAM/SOM analysis, and competitive landscape research.", M.GENERAL_LLAMA, ["market-research", "tam-sam-som", "competitive-analysis", "trends", "segments"], 9),
  a("research-competitive", "Competitive Intelligence Analyst", "research", "competitive", "Deep competitor analysis, feature comparison, and market positioning.", M.REASONING_LARGE, ["competitive-intelligence", "feature-comparison", "swot", "positioning", "benchmarking"], 9),
  a("research-fact-check", "Fact Checker", "research", "verification", "Rigorous fact verification, source cross-referencing, and claim validation.", M.REASONING_LARGE, ["fact-checking", "verification", "sources", "claims", "accuracy"], 8),
  a("research-news", "News & Trend Analyst", "research", "news", "Current events analysis, trend identification, and news synthesis.", M.GENERAL_QWEN, ["news", "trends", "current-events", "analysis", "synthesis"], 7),
  a("research-tech-spec", "Technical Specification Analyst", "research", "technical", "Analyzes RFCs, technical specs, standards documents, and API documentation.", M.REASONING_LARGE, ["specs", "rfc", "standards", "api-docs", "technical-analysis"], 8),
  a("research-patent", "Patent Researcher", "research", "legal", "Patent landscape analysis, prior art research, and IP assessment.", M.GENERAL_SUPER, ["patents", "prior-art", "ip", "claims", "patent-analysis"], 7),
  a("research-survey", "Survey & Data Analyst", "research", "surveys", "Survey design, response analysis, and statistical summarization.", M.GENERAL_QWEN, ["surveys", "statistics", "analysis", "insights", "reporting"], 7),
  a("research-trend", "Trend & Futures Analyst", "research", "trends", "Emerging technology trends, signal detection, and future scenario planning.", M.GENERAL_ULTRA, ["trends", "emerging-tech", "futures", "signals", "scenarios"], 8),
  a("research-domain-expert", "Domain Knowledge Expert", "research", "domain", "Deep domain expertise across multiple fields for specialized research.", M.GENERAL_ULTRA, ["domain-expertise", "specialized-knowledge", "cross-domain", "synthesis"], 8),
  a("research-literature", "Literature Review Specialist", "research", "academic", "Systematic literature reviews with thematic analysis and gap identification.", M.GENERAL_SUPER, ["literature-review", "systematic-review", "thematic-analysis", "gaps", "meta-analysis"], 8),
  a("research-ux", "UX Research Analyst", "research", "ux", "User research methods, persona development, and usability analysis.", M.GENERAL_LLAMA, ["ux-research", "personas", "usability", "user-interviews", "journey-mapping"], 7),
  a("research-finance", "Financial Research Analyst", "research", "finance", "Company financials, valuation metrics, and investment thesis research.", M.REASONING_LARGE, ["financial-research", "valuation", "metrics", "investment", "due-diligence"], 8),
  a("research-scientific", "Scientific Literature Analyst", "research", "science", "Scientific paper analysis, methodology evaluation, and reproducibility assessment.", M.GENERAL_ULTRA, ["science", "papers", "methodology", "reproducibility", "citations"], 8),
  a("research-social", "Social Media & Sentiment Analyst", "research", "social", "Social media trends, sentiment analysis, and audience behavior.", M.GENERAL_GEMMA31, ["social-media", "sentiment", "audience", "trends", "engagement"], 7),
  a("research-geopolitical", "Geopolitical Analyst", "research", "geopolitics", "Geopolitical risk assessment, regional analysis, and international relations.", M.GENERAL_ULTRA, ["geopolitics", "risk", "regions", "international", "policy"], 7),
  a("research-regulatory", "Regulatory & Compliance Researcher", "research", "regulatory", "Regulatory landscape, compliance requirements, and policy analysis.", M.REASONING_LARGE, ["regulatory", "compliance", "policy", "gdpr", "standards"], 8),
  a("research-customer", "Customer Research Analyst", "research", "customer", "Customer behavior, pain points, and voice-of-customer analysis.", M.GENERAL_LLAMA, ["customer-research", "voc", "pain-points", "behavior", "segmentation"], 8),
  a("research-technology", "Technology Assessment Analyst", "research", "technology", "Technology evaluation, stack comparison, and build-vs-buy analysis.", M.REASONING_LARGE, ["tech-assessment", "comparison", "build-vs-buy", "trade-offs", "evaluation"], 8),
  a("research-benchmark", "Benchmarking Analyst", "research", "benchmarks", "Performance benchmarking, industry standards comparison, and KPI analysis.", M.GENERAL_QWEN, ["benchmarking", "kpis", "industry-standards", "performance", "comparison"], 7),
  a("research-citation", "Citation & Reference Manager", "research", "citations", "Structures references, validates citations, and creates bibliographies.", M.GENERAL_NANO30, ["citations", "references", "bibliography", "apa", "academic-writing"], 6),
  a("research-pricing", "Pricing Research Analyst", "research", "pricing", "Competitive pricing analysis, price sensitivity, and pricing model research.", M.GENERAL_QWEN, ["pricing", "competitive-pricing", "value-based", "elasticity", "models"], 8),
  a("research-case-study", "Case Study Analyst", "research", "case-studies", "Case study research, success/failure pattern analysis, and lessons extraction.", M.GENERAL_LLAMA, ["case-studies", "patterns", "lessons", "analysis", "frameworks"], 7),
  a("research-ecosystem", "Ecosystem & Partnership Analyst", "research", "ecosystem", "Technology ecosystem mapping, partnership opportunities, and integration landscapes.", M.GENERAL_QWEN, ["ecosystem", "partnerships", "integrations", "landscape", "mapping"], 7),
  a("research-user-story", "User Story Researcher", "research", "requirements", "Extracts user stories from research data, identifies epics, and maps journeys.", M.GENERAL_LLAMA, ["user-stories", "epics", "requirements", "journeys", "acceptance-criteria"], 7),
  a("research-keyword", "SEO & Keyword Researcher", "research", "seo", "Keyword research, search volume analysis, and content gap identification.", M.GENERAL_NANO30, ["keywords", "seo", "search-volume", "content-gaps", "serp"], 7),
  a("research-api-explorer", "API & Integration Researcher", "research", "apis", "Researches third-party APIs, evaluates SDKs, and documents integration options.", M.CODER_MEDIUM, ["api-research", "sdks", "integrations", "documentation", "evaluation"], 7),
  a("research-opendata", "Open Data Analyst", "research", "data", "Finds, evaluates, and synthesizes open datasets and public data sources.", M.GENERAL_QWEN, ["open-data", "datasets", "public-data", "evaluation", "synthesis"], 7),
  a("research-risk", "Risk Research Analyst", "research", "risk", "Risk identification, probability assessment, and mitigation strategy research.", M.REASONING_LARGE, ["risk-research", "risk-matrix", "mitigation", "probability", "impact"], 8),
  a("research-competitor-product", "Product Competitor Analyst", "research", "product", "Analyzes competitor products, features, roadmaps, and positioning.", M.REASONING_LARGE, ["product-analysis", "features", "roadmap", "positioning", "differentiation"], 8),
  a("research-health", "Healthcare & Medical Researcher", "research", "health", "Medical literature research, clinical study analysis, and health data.", M.GENERAL_ULTRA, ["medical", "clinical", "health-data", "research", "evidence-based"], 7),
  a("research-climate", "Climate & Sustainability Researcher", "research", "sustainability", "Climate data analysis, sustainability metrics, and ESG research.", M.GENERAL_SUPER, ["climate", "sustainability", "esg", "carbon", "environment"], 7),
  a("research-education", "Education Research Analyst", "research", "education", "Educational content research, learning methodology analysis, and curriculum gaps.", M.GENERAL_LLAMA, ["education", "learning", "curriculum", "pedagogy", "research"], 6),
  a("research-supply-chain", "Supply Chain Researcher", "research", "supply-chain", "Supply chain analysis, vendor research, and logistics optimization research.", M.GENERAL_QWEN, ["supply-chain", "vendors", "logistics", "procurement", "analysis"], 7),

  // ── WRITING DOMAIN (30 agents) ──────────────────────────────────────────
  a("write-technical", "Technical Writer", "writing", "technical", "Produces clear, accurate technical documentation, guides, and manuals.", M.GENERAL_LLAMA, ["technical-writing", "documentation", "clarity", "accuracy", "structure"], 9),
  a("write-blog", "Blog Post Writer", "writing", "content", "Writes engaging, SEO-optimized blog posts with hooks, structure, and CTAs.", M.CREATIVE, ["blog-writing", "seo", "engagement", "hooks", "storytelling"], 8),
  a("write-api-docs", "API Documentation Writer", "writing", "technical", "Writes developer-focused API documentation with examples, SDKs, and quick-starts.", M.CODER_MEDIUM, ["api-docs", "openapi", "examples", "developer-experience", "reference"], 9),
  a("write-marketing", "Marketing Copy Writer", "writing", "marketing", "Writes compelling marketing copy: landing pages, ads, email campaigns, and taglines.", M.CREATIVE, ["marketing", "copywriting", "conversion", "landing-pages", "email"], 9),
  a("write-ux-copy", "UX Copy Writer", "writing", "ux", "Microcopy, error messages, onboarding flows, and interface text.", M.GENERAL_GEMMA31, ["ux-writing", "microcopy", "error-messages", "onboarding", "clarity"], 8),
  a("write-email", "Email Campaign Writer", "writing", "email", "Email sequences, newsletters, drip campaigns, and transactional emails.", M.CREATIVE, ["email", "campaigns", "drip", "newsletters", "transactional"], 8),
  a("write-press-release", "Press Release Writer", "writing", "pr", "Professional press releases with inverted pyramid structure and AP style.", M.GENERAL_LLAMA, ["press-release", "pr", "ap-style", "news", "media"], 7),
  a("write-product-desc", "Product Description Writer", "writing", "ecommerce", "E-commerce product descriptions that convert with features, benefits, and storytelling.", M.CREATIVE, ["product-descriptions", "ecommerce", "benefits", "storytelling", "seo"], 7),
  a("write-seo-content", "SEO Content Writer", "writing", "seo", "Search-optimized content with proper keyword density, structure, and meta descriptions.", M.GENERAL_GEMMA31, ["seo-writing", "keywords", "meta", "search-intent", "e-e-a-t"], 8),
  a("write-creative", "Creative Writer", "writing", "creative", "Original fiction, world-building, character development, and narrative writing.", M.CREATIVE, ["creative-writing", "fiction", "narrative", "characters", "world-building"], 8),
  a("write-editor", "Editor & Proofreader", "writing", "editing", "Copyediting, proofreading, grammar, style consistency, and clarity improvements.", M.GENERAL_LLAMA, ["editing", "proofreading", "grammar", "style", "clarity"], 8),
  a("write-report", "Business Report Writer", "writing", "business", "Executive reports, case studies, white papers, and business analysis documents.", M.GENERAL_SUPER, ["reports", "white-papers", "executive-summary", "case-studies", "analysis"], 8),
  a("write-proposal", "Proposal Writer", "writing", "business", "Business proposals, RFP responses, grant proposals, and project scopes.", M.REASONING_LARGE, ["proposals", "rfp", "grants", "scope", "persuasion"], 8),
  a("write-script-video", "Video Script Writer", "writing", "video", "YouTube scripts, explainer videos, product demos, and course content.", M.CREATIVE, ["video-scripts", "youtube", "explainer", "hooks", "storytelling"], 8),
  a("write-speech", "Speech & Presentation Writer", "writing", "speeches", "Keynote speeches, conference talks, and persuasive presentations.", M.GENERAL_ULTRA, ["speeches", "keynote", "presentations", "persuasion", "narrative"], 7),
  a("write-social", "Social Media Content Writer", "writing", "social", "Platform-specific social content: Twitter threads, LinkedIn posts, Instagram captions.", M.CREATIVE, ["social-media", "threads", "linkedin", "instagram", "engagement"], 8),
  a("write-README", "README Writer", "writing", "technical", "GitHub README files with badges, installation, usage, and contribution guides.", M.CODER_MEDIUM, ["readme", "github", "installation", "usage", "badges"], 8),
  a("write-changelog", "Changelog Writer", "writing", "technical", "Release notes, changelogs, and migration guides from code diffs or feature lists.", M.CODER_MEDIUM, ["changelog", "release-notes", "migration-guide", "versioning", "breaking-changes"], 7),
  a("write-legal", "Legal Document Drafting Assistant", "writing", "legal", "Terms of Service, Privacy Policy, NDA, and basic legal document drafting.", M.GENERAL_SUPER, ["legal", "tos", "privacy-policy", "nda", "contracts"], 7),
  a("write-knowledge-base", "Knowledge Base Author", "writing", "documentation", "Help center articles, FAQs, troubleshooting guides, and support documentation.", M.GENERAL_LLAMA, ["knowledge-base", "help-center", "faq", "troubleshooting", "support"], 7),
  a("write-onboarding", "Onboarding Content Writer", "writing", "ux", "Product onboarding flows, welcome sequences, and user activation content.", M.CREATIVE, ["onboarding", "activation", "welcome", "tutorial", "user-education"], 7),
  a("write-brand-voice", "Brand Voice Developer", "writing", "branding", "Brand voice guidelines, tone-of-voice frameworks, and messaging pillars.", M.CREATIVE, ["brand-voice", "tone-of-voice", "messaging", "brand-guidelines", "personality"], 8),
  a("write-academic", "Academic Writer", "writing", "academic", "Academic papers, essays, literature reviews, and thesis sections.", M.GENERAL_ULTRA, ["academic-writing", "papers", "citations", "structure", "argumentation"], 7),
  a("write-podcast", "Podcast Script Writer", "writing", "audio", "Podcast episode outlines, interview scripts, and show notes.", M.CREATIVE, ["podcast", "scripts", "show-notes", "interviews", "storytelling"], 7),
  a("write-case-study", "Case Study Writer", "writing", "marketing", "Customer case studies, success stories, and testimonial-driven narratives.", M.GENERAL_LLAMA, ["case-studies", "success-stories", "testimonials", "roi", "storytelling"], 7),
  a("write-newsletter", "Newsletter Writer", "writing", "content", "Weekly/monthly newsletters with curated insights, analysis, and engagement hooks.", M.GENERAL_GEMMA31, ["newsletter", "curation", "insights", "engagement", "subscribers"], 7),
  a("write-grant", "Grant Proposal Writer", "writing", "nonprofit", "Grant applications, funding proposals, and impact reports.", M.GENERAL_SUPER, ["grants", "funding", "impact", "proposals", "nonprofit"], 6),
  a("write-user-manual", "User Manual Writer", "writing", "technical", "Step-by-step user manuals, installation guides, and product documentation.", M.GENERAL_LLAMA, ["user-manuals", "installation", "step-by-step", "screenshots", "clarity"], 7),
  a("write-data-story", "Data Storyteller", "writing", "data", "Translates data insights into compelling narratives for non-technical audiences.", M.GENERAL_GEMMA31, ["data-storytelling", "narrative", "insights", "visualization", "communication"], 8),
  a("write-pitch", "Pitch Deck Writer", "writing", "business", "Startup pitch decks, investor presentations, and executive summaries.", M.REASONING_LARGE, ["pitch-deck", "investor", "startup", "narrative", "valuation"], 8),

  // ── DATA DOMAIN (25 agents) ─────────────────────────────────────────────
  a("data-analyst", "Data Analyst", "data", "analysis", "Statistical analysis, trend identification, and insight generation from datasets.", M.REASONING_NANO, ["statistics", "analysis", "trends", "insights", "visualization"], 9),
  a("data-sql-expert", "SQL Query Expert", "data", "sql", "Complex SQL queries, window functions, CTEs, and query optimization.", M.CODER_LARGE, ["sql", "queries", "window-functions", "cte", "optimization"], 9),
  a("data-etl", "ETL Pipeline Designer", "data", "engineering", "ETL/ELT pipeline design with dbt, Airflow, and Spark.", M.GENERAL_QWEN, ["etl", "dbt", "airflow", "spark", "data-pipelines"], 8),
  a("data-viz", "Data Visualization Specialist", "data", "visualization", "Chart selection, dashboard design, and data visualization best practices.", M.GENERAL_GEMMA26, ["visualization", "charts", "dashboards", "d3", "tableau"], 8),
  a("data-ml-features", "ML Feature Engineer", "data", "ml", "Feature selection, engineering, and transformation for machine learning models.", M.REASONING_NANO, ["feature-engineering", "ml", "transformations", "selection", "pipelines"], 8),
  a("data-cleaner", "Data Cleaning Specialist", "data", "quality", "Data quality assessment, cleaning strategies, and outlier detection.", M.GENERAL_QWEN, ["data-cleaning", "quality", "outliers", "missing-values", "normalization"], 7),
  a("data-schema", "Data Schema Architect", "data", "modeling", "Data warehouse schema design: star schema, snowflake, and data vault.", M.GENERAL_SUPER, ["data-modeling", "star-schema", "snowflake", "data-warehouse", "dimensions"], 8),
  a("data-metrics", "Metrics & KPI Designer", "data", "metrics", "Defines KPIs, metric trees, and measurement frameworks.", M.REASONING_LARGE, ["kpis", "metrics", "measurement", "north-star", "OKRs"], 8),
  a("data-ab-test", "A/B Testing Analyst", "data", "experiments", "Experiment design, statistical significance, and A/B test analysis.", M.REASONING_NANO, ["ab-testing", "statistics", "significance", "experiments", "conversion"], 8),
  a("data-pandas", "Pandas Data Processor", "data", "python", "Data manipulation with pandas, data cleaning, and transformation scripts.", M.CODER_MEDIUM, ["pandas", "dataframes", "cleaning", "transformation", "aggregation"], 8),
  a("data-bi", "Business Intelligence Analyst", "data", "bi", "BI dashboard design, report creation, and business metric analysis.", M.GENERAL_LLAMA, ["bi", "dashboards", "reports", "metrics", "tableau"], 7),
  a("data-regression", "Statistical Regression Analyst", "data", "statistics", "Linear/logistic regression, correlation analysis, and predictive modeling.", M.REASONING_NANO, ["regression", "statistics", "correlation", "prediction", "r-squared"], 7),
  a("data-nlp-basic", "Text Data Analyst", "data", "nlp", "Text preprocessing, TF-IDF, sentiment analysis, and basic NLP tasks.", M.GENERAL_QWEN, ["nlp", "text-analysis", "sentiment", "tfidf", "tokenization"], 7),
  a("data-time-series", "Time Series Analyst", "data", "statistics", "Time series forecasting, seasonality, trend decomposition, and anomaly detection.", M.REASONING_NANO, ["time-series", "forecasting", "seasonality", "arima", "anomaly"], 8),
  a("data-json-xml", "JSON/XML Data Transformer", "data", "transformation", "JSON/XML parsing, transformation, schema validation, and data format conversion.", M.CODER_MEDIUM, ["json", "xml", "transformation", "schema-validation", "conversion"], 7),
  a("data-csv", "CSV Data Processor", "data", "files", "CSV processing, large file handling, and tabular data manipulation.", M.CODER_MEDIUM, ["csv", "tabular", "processing", "large-files", "cleaning"], 6),
  a("data-api-analytics", "API Analytics Designer", "data", "analytics", "API usage analytics, endpoint performance metrics, and usage pattern analysis.", M.GENERAL_QWEN, ["api-analytics", "usage", "performance", "patterns", "metrics"], 7),
  a("data-cohort", "Cohort Analysis Specialist", "data", "analytics", "User cohort analysis, retention curves, and churn prediction.", M.REASONING_NANO, ["cohort", "retention", "churn", "ltv", "funnel"], 8),
  a("data-funnel", "Funnel Analytics Specialist", "data", "analytics", "Conversion funnel analysis, drop-off identification, and optimization recommendations.", M.REASONING_NANO, ["funnel", "conversion", "drop-off", "optimization", "metrics"], 8),
  a("data-reporting", "Automated Report Generator", "data", "reporting", "Automated reporting templates, scheduled reports, and data digest generation.", M.GENERAL_GEMMA31, ["reporting", "automation", "templates", "scheduling", "digests"], 7),
  a("data-cost", "Cloud Cost Analyst", "data", "cost", "Cloud infrastructure cost analysis, optimization opportunities, and budget forecasting.", M.GENERAL_LLAMA, ["cloud-cost", "optimization", "aws", "gcp", "budget"], 7),
  a("data-logs", "Log Analysis Specialist", "data", "operations", "Log parsing, pattern detection, error rate analysis, and log aggregation strategies.", M.CODER_MEDIUM, ["logs", "parsing", "patterns", "errors", "aggregation"], 7),
  a("data-graph", "Graph Data Analyst", "data", "graph", "Graph database queries, network analysis, and relationship mapping with Neo4j/DGraph.", M.GENERAL_QWEN, ["graph", "neo4j", "network-analysis", "relationships", "cypher"], 7),
  a("data-privacy", "Data Privacy Analyst", "data", "privacy", "PII detection, data classification, GDPR compliance analysis, and anonymization.", M.REASONING_LARGE, ["privacy", "pii", "gdpr", "anonymization", "data-classification"], 8),
  a("data-quality-monitor", "Data Quality Monitor", "data", "quality", "Data quality rules, anomaly scoring, freshness checks, and quality dashboards.", M.GENERAL_QWEN, ["data-quality", "anomalies", "freshness", "rules", "monitoring"], 7),

  // ── SECURITY DOMAIN (25 agents) ─────────────────────────────────────────
  a("sec-auditor", "Security Auditor", "security", "audit", "Comprehensive security audit covering code, infrastructure, and configurations.", M.REASONING_LARGE, ["security-audit", "vulnerabilities", "risks", "compliance", "hardening"], 9),
  a("sec-owasp", "OWASP Analyst", "security", "web", "OWASP Top 10 analysis, web vulnerability assessment, and remediation guidance.", M.REASONING_LARGE, ["owasp", "xss", "sqli", "csrf", "injection"], 9),
  a("sec-pentest-planner", "Penetration Test Planner", "security", "pentest", "Penetration testing methodology, test plan creation, and vulnerability discovery.", M.GENERAL_SUPER, ["pentest", "methodology", "red-team", "vulnerabilities", "attack-vectors"], 8),
  a("sec-code-scanner", "Code Vulnerability Scanner", "security", "sast", "Static code analysis for security vulnerabilities, secrets, and unsafe patterns.", M.CODER_LARGE, ["sast", "code-scanning", "vulnerabilities", "secrets", "unsafe-patterns"], 9),
  a("sec-deps", "Dependency Vulnerability Auditor", "security", "dependencies", "NPM/pip/cargo dependency audits, CVE scanning, and update recommendations.", M.CODER_MEDIUM, ["dependencies", "cve", "npm-audit", "supply-chain", "updates"], 8),
  a("sec-secrets", "Secret Scanner", "security", "secrets", "Identifies hardcoded secrets, API keys, passwords, and credentials in code.", M.CODER_MEDIUM, ["secrets", "api-keys", "credentials", "env-vars", "vault"], 9),
  a("sec-api-security", "API Security Analyst", "security", "api", "API authentication, authorization, rate limiting, and injection vulnerability analysis.", M.REASONING_LARGE, ["api-security", "auth", "rate-limiting", "injection", "jwt"], 9),
  a("sec-auth-reviewer", "Authentication & Authorization Reviewer", "security", "auth", "Auth flow analysis, privilege escalation, session management, and token security.", M.REASONING_LARGE, ["auth", "authorization", "sessions", "jwt", "privilege-escalation"], 9),
  a("sec-infra", "Infrastructure Security Analyst", "security", "infrastructure", "Cloud infrastructure security: IAM, network policies, encryption, and least privilege.", M.GENERAL_SUPER, ["iam", "network-security", "encryption", "cloud-security", "least-privilege"], 8),
  a("sec-network", "Network Security Analyst", "security", "network", "Network architecture security, firewall rules, VPN configuration, and DDoS mitigation.", M.GENERAL_SUPER, ["network-security", "firewall", "vpn", "ddos", "zero-trust"], 8),
  a("sec-container", "Container Security Analyst", "security", "containers", "Docker/Kubernetes security, image scanning, RBAC, and pod security policies.", M.CODER_POOLSIDE_M, ["containers", "docker", "kubernetes", "rbac", "image-scanning"], 8),
  a("sec-compliance", "Security Compliance Analyst", "security", "compliance", "SOC2, GDPR, HIPAA, PCI-DSS compliance gap analysis and remediation planning.", M.GENERAL_SUPER, ["soc2", "gdpr", "hipaa", "pci-dss", "compliance"], 8),
  a("sec-cryptography", "Cryptography Reviewer", "security", "crypto", "Cryptographic implementation review, algorithm selection, and key management.", M.REASONING_LARGE, ["cryptography", "algorithms", "key-management", "tls", "implementation"], 7),
  a("sec-threat-model", "Threat Modeling Specialist", "security", "threat-modeling", "STRIDE, DREAD, and attack tree threat modeling for systems and applications.", M.GENERAL_ULTRA, ["threat-modeling", "stride", "attack-trees", "mitigations", "risk"], 8),
  a("sec-incident", "Incident Response Planner", "security", "incidents", "Security incident response playbooks, breach analysis, and recovery planning.", M.REASONING_LARGE, ["incident-response", "playbooks", "breach", "recovery", "forensics"], 7),
  a("sec-phishing", "Phishing & Social Engineering Analyst", "security", "social", "Phishing simulation planning, social engineering vectors, and user awareness training.", M.GENERAL_LLAMA, ["phishing", "social-engineering", "awareness", "training", "vectors"], 7),
  a("sec-siem", "SIEM & Monitoring Analyst", "security", "monitoring", "Security monitoring, SIEM rules, alert tuning, and SOC workflow design.", M.GENERAL_SUPER, ["siem", "monitoring", "alerts", "soc", "detection"], 7),
  a("sec-vuln-mgmt", "Vulnerability Management Specialist", "security", "vulnerabilities", "Vulnerability prioritization, CVSS scoring, and remediation tracking.", M.REASONING_LARGE, ["vulnerability-management", "cvss", "prioritization", "remediation", "tracking"], 8),
  a("sec-data-protection", "Data Protection Officer", "security", "data", "Data protection impact assessments, DPA policies, and breach notification procedures.", M.GENERAL_SUPER, ["data-protection", "dpia", "policies", "breach-notification", "gdpr"], 7),
  a("sec-mobile", "Mobile Security Analyst", "security", "mobile", "iOS and Android security: certificate pinning, keychain, and API security.", M.REASONING_LARGE, ["mobile-security", "ios", "android", "certificate-pinning", "keychain"], 7),
  a("sec-iot", "IoT Security Analyst", "security", "iot", "IoT device security, firmware analysis, and embedded system vulnerability assessment.", M.GENERAL_SUPER, ["iot-security", "firmware", "embedded", "protocols", "vulnerabilities"], 7),
  a("sec-devsecops", "DevSecOps Engineer", "security", "devsecops", "Security in CI/CD pipelines, shift-left security, and automated security testing.", M.CODER_POOLSIDE_M, ["devsecops", "cicd", "shift-left", "automated-testing", "pipelines"], 8),
  a("sec-zero-trust", "Zero Trust Architect", "security", "architecture", "Zero trust network architecture, identity-first security, and microsegmentation.", M.GENERAL_ULTRA, ["zero-trust", "microsegmentation", "identity", "access-control", "architecture"], 7),
  a("sec-cloud-posture", "Cloud Security Posture Manager", "security", "cloud", "Cloud security posture review, misconfiguration detection, and CIS benchmark assessment.", M.GENERAL_SUPER, ["cloud-posture", "misconfigurations", "cis-benchmark", "aws", "gcp"], 8),
  a("sec-content-safety", "Content Safety Reviewer", "security", "content", "Content moderation, harmful content detection, and platform safety policies.", M.SAFETY, ["content-safety", "moderation", "harmful-content", "policies", "classification"], 8),

  // ── DEVOPS DOMAIN (25 agents) ────────────────────────────────────────────
  a("devops-docker", "Docker Specialist", "devops", "containers", "Docker image optimization, multi-stage builds, networking, and Compose configurations.", M.CODER_POOLSIDE_M, ["docker", "containers", "multi-stage", "compose", "networking"], 9),
  a("devops-kubernetes", "Kubernetes Architect", "devops", "kubernetes", "Kubernetes deployments, services, ingress, HPA, and cluster management.", M.GENERAL_SUPER, ["kubernetes", "helm", "ingress", "hpa", "rbac"], 9),
  a("devops-cicd-github", "GitHub Actions CI/CD Engineer", "devops", "cicd", "GitHub Actions workflows, reusable workflows, matrix builds, and deployment pipelines.", M.CODER_POOLSIDE_M, ["github-actions", "cicd", "workflows", "matrix", "deployment"], 9),
  a("devops-cicd-gitlab", "GitLab CI/CD Engineer", "devops", "cicd", "GitLab CI/CD pipelines, runners, environments, and Auto DevOps.", M.CODER_POOLSIDE_M, ["gitlab-ci", "pipelines", "runners", "environments", "auto-devops"], 8),
  a("devops-aws", "AWS Cloud Architect", "devops", "cloud", "AWS services, architecture, IAM, networking, and cost optimization.", M.GENERAL_SUPER, ["aws", "ec2", "ecs", "lambda", "vpc"], 9),
  a("devops-gcp", "GCP Cloud Architect", "devops", "cloud", "Google Cloud Platform architecture, GKE, Cloud Run, and BigQuery.", M.GENERAL_SUPER, ["gcp", "gke", "cloud-run", "bigquery", "iam"], 8),
  a("devops-azure", "Azure Cloud Architect", "devops", "cloud", "Azure architecture, AKS, Azure Functions, and Active Directory.", M.GENERAL_SUPER, ["azure", "aks", "functions", "active-directory", "devops"], 8),
  a("devops-monitoring", "Observability Engineer", "devops", "monitoring", "Prometheus, Grafana, OpenTelemetry, and distributed tracing setup.", M.GENERAL_LLAMA, ["prometheus", "grafana", "opentelemetry", "tracing", "alerting"], 8),
  a("devops-logging", "Logging Infrastructure Engineer", "devops", "logging", "ELK Stack, Loki, Fluentd, and centralized log management.", M.GENERAL_LLAMA, ["elk", "loki", "fluentd", "log-management", "retention"], 7),
  a("devops-terraform", "Terraform Infrastructure Engineer", "devops", "iac", "Terraform modules, state management, remote backends, and workspace strategies.", M.CODER_POOLSIDE_M, ["terraform", "modules", "state", "workspaces", "providers"], 8),
  a("devops-helm", "Helm Charts Developer", "devops", "kubernetes", "Helm chart creation, values management, chart testing, and Helm repositories.", M.CODER_POOLSIDE_M, ["helm", "charts", "values", "templating", "repositories"], 8),
  a("devops-serverless", "Serverless Architect", "devops", "serverless", "AWS Lambda, Google Cloud Functions, Cloudflare Workers, and event-driven serverless.", M.GENERAL_LLAMA, ["serverless", "lambda", "cloud-functions", "workers", "event-driven"], 8),
  a("devops-networking", "Cloud Networking Engineer", "devops", "networking", "VPC, subnets, security groups, load balancers, and private networking.", M.GENERAL_SUPER, ["vpc", "networking", "load-balancers", "security-groups", "dns"], 7),
  a("devops-db-ops", "Database Operations Engineer", "devops", "databases", "Database backup, replication, failover, connection pooling, and performance tuning.", M.GENERAL_LLAMA, ["db-ops", "replication", "failover", "pgbouncer", "backups"], 8),
  a("devops-gitops", "GitOps Practitioner", "devops", "gitops", "ArgoCD, Flux, GitOps workflows, and declarative infrastructure management.", M.CODER_POOLSIDE_M, ["gitops", "argocd", "flux", "declarative", "reconciliation"], 7),
  a("devops-scaling", "Auto-Scaling Engineer", "devops", "scaling", "Horizontal/vertical scaling, load testing, capacity planning, and traffic management.", M.GENERAL_SUPER, ["scaling", "load-testing", "capacity-planning", "hpa", "traffic"], 8),
  a("devops-disaster-recovery", "Disaster Recovery Planner", "devops", "reliability", "DR strategies, RTO/RPO objectives, backup validation, and failover testing.", M.GENERAL_SUPER, ["disaster-recovery", "rto", "rpo", "backup", "failover"], 7),
  a("devops-cost-optimization", "Cloud Cost Engineer", "devops", "cost", "Cloud cost analysis, reserved instances, spot instances, and FinOps practices.", M.GENERAL_LLAMA, ["finops", "cost-optimization", "reserved-instances", "spot", "rightsizing"], 8),
  a("devops-sre", "Site Reliability Engineer", "devops", "sre", "SLOs, SLIs, error budgets, toil reduction, and reliability engineering.", M.GENERAL_SUPER, ["sre", "slos", "slis", "error-budgets", "toil-reduction"], 8),
  a("devops-vault", "HashiCorp Vault Engineer", "devops", "secrets", "Vault setup, secret engines, policies, dynamic secrets, and PKI management.", M.CODER_POOLSIDE_M, ["vault", "secrets", "pki", "dynamic-secrets", "policies"], 7),
  a("devops-istio", "Service Mesh Engineer", "devops", "networking", "Istio, Linkerd, traffic management, mTLS, and observability in service meshes.", M.GENERAL_SUPER, ["istio", "linkerd", "service-mesh", "mtls", "traffic-management"], 7),
  a("devops-jenkins", "Jenkins Pipeline Engineer", "devops", "cicd", "Jenkins pipeline design, shared libraries, and plugin configuration.", M.CODER_POOLSIDE_M, ["jenkins", "pipelines", "groovy", "shared-libraries", "plugins"], 7),
  a("devops-ansible", "Ansible Automation Engineer", "devops", "configuration", "Ansible playbooks, roles, inventories, and configuration management.", M.CODER_POOLSIDE_M, ["ansible", "playbooks", "roles", "idempotent", "configuration"], 7),
  a("devops-cdn", "CDN & Edge Engineer", "devops", "edge", "CDN configuration, edge caching, Cloudflare Workers, and global distribution.", M.GENERAL_LLAMA, ["cdn", "edge", "cloudflare", "caching", "global-distribution"], 7),
  a("devops-release", "Release Manager", "devops", "releases", "Release planning, semantic versioning, deployment strategies, and rollback procedures.", M.GENERAL_LLAMA, ["release-management", "semver", "blue-green", "canary", "rollback"], 8),

  // ── AI/ML DOMAIN (20 agents) ─────────────────────────────────────────────
  a("aiml-model-selector", "ML Model Selector", "aiml", "selection", "Evaluates and recommends the best ML models for specific tasks and constraints.", M.REASONING_NANO, ["model-selection", "benchmarks", "trade-offs", "evaluation", "criteria"], 9),
  a("aiml-prompt-engineer", "Prompt Engineer", "aiml", "prompting", "Expert prompt engineering: chain-of-thought, few-shot, and system prompt optimization.", M.REASONING_LARGE, ["prompt-engineering", "cot", "few-shot", "system-prompts", "optimization"], 9),
  a("aiml-rag-architect", "RAG Architect", "aiml", "rag", "Retrieval-Augmented Generation design: chunking, embedding, and retrieval strategies.", M.REASONING_LARGE, ["rag", "embeddings", "vector-db", "chunking", "retrieval"], 9),
  a("aiml-vector-db", "Vector Database Specialist", "aiml", "vector-db", "Pinecone, Weaviate, Chroma, and pgvector setup, indexing, and querying.", M.CODER_LARGE, ["vector-db", "pinecone", "weaviate", "chroma", "embeddings"], 8),
  a("aiml-fine-tuning", "Fine-Tuning Specialist", "aiml", "fine-tuning", "LoRA, QLoRA, and supervised fine-tuning strategies for LLMs.", M.GENERAL_ULTRA, ["fine-tuning", "lora", "qlora", "datasets", "training"], 8),
  a("aiml-agent-designer", "AI Agent Designer", "aiml", "agents", "Multi-agent system design, tool use, memory patterns, and agent orchestration.", M.REASONING_LARGE, ["agents", "tools", "memory", "orchestration", "planning"], 9),
  a("aiml-mlops", "MLOps Engineer", "aiml", "mlops", "ML pipeline automation, model versioning, monitoring, and deployment.", M.GENERAL_SUPER, ["mlops", "mlflow", "model-versioning", "monitoring", "deployment"], 8),
  a("aiml-eval", "AI Evaluation Specialist", "aiml", "evaluation", "LLM evaluation frameworks, benchmarks, human eval design, and hallucination testing.", M.REASONING_LARGE, ["evaluation", "benchmarks", "hallucination", "metrics", "evals"], 8),
  a("aiml-dataset", "Dataset Curator", "aiml", "data", "Training dataset creation, curation, deduplication, and quality filtering.", M.GENERAL_QWEN, ["datasets", "curation", "deduplication", "quality", "annotation"], 7),
  a("aiml-computer-vision", "Computer Vision Engineer", "aiml", "vision", "Image classification, object detection, segmentation, and vision model integration.", M.VISION, ["computer-vision", "detection", "segmentation", "yolo", "transformers"], 7),
  a("aiml-nlp", "NLP Specialist", "aiml", "nlp", "NLP pipelines, tokenization, named entity recognition, and text classification.", M.REASONING_NANO, ["nlp", "ner", "classification", "tokenization", "transformers"], 8),
  a("aiml-llm-integration", "LLM Integration Developer", "aiml", "integration", "Integrating LLMs into applications: streaming, function calling, and structured output.", M.CODER_LARGE, ["llm-integration", "streaming", "function-calling", "structured-output", "openai"], 9),
  a("aiml-guardrails", "AI Safety & Guardrails Engineer", "aiml", "safety", "Implements AI guardrails, content filtering, and responsible AI practices.", M.SAFETY, ["guardrails", "content-filtering", "safety", "responsible-ai", "red-teaming"], 8),
  a("aiml-recommendations", "Recommendation System Designer", "aiml", "recommendations", "Collaborative filtering, content-based, and hybrid recommendation architectures.", M.REASONING_NANO, ["recommendations", "collaborative-filtering", "content-based", "matrix-factorization", "ranking"], 7),
  a("aiml-knowledge-graph", "Knowledge Graph Engineer", "aiml", "knowledge", "Knowledge graph construction, entity linking, ontology design, and graph embeddings.", M.GENERAL_ULTRA, ["knowledge-graph", "ontology", "entity-linking", "embeddings", "rdf"], 8),
  a("aiml-speech", "Speech Processing Engineer", "aiml", "speech", "ASR, TTS, speaker diarization, and audio processing pipelines.", M.GENERAL_QWEN, ["speech", "asr", "tts", "diarization", "audio-processing"], 7),
  a("aiml-multimodal", "Multimodal AI Engineer", "aiml", "multimodal", "Vision-language models, cross-modal fusion, and multimodal pipeline design.", M.VISION, ["multimodal", "vision-language", "cross-modal", "gemini", "gpt-4v"], 8),
  a("aiml-training-data", "Synthetic Training Data Generator", "aiml", "data", "Synthetic data generation, data augmentation, and privacy-preserving datasets.", M.GENERAL_SUPER, ["synthetic-data", "augmentation", "privacy", "generation", "quality"], 7),
  a("aiml-cost-optimizer", "AI Cost Optimizer", "aiml", "cost", "LLM cost optimization: model routing, caching, batching, and token reduction.", M.REASONING_NANO, ["cost-optimization", "model-routing", "caching", "batching", "tokens"], 8),
  a("aiml-graph-neural", "Graph Neural Network Specialist", "aiml", "gnn", "GNN architectures, graph learning, and molecular/social network applications.", M.GENERAL_ULTRA, ["gnn", "graph-learning", "pytorch-geometric", "molecules", "networks"], 6),

  // ── DESIGN DOMAIN (20 agents) ────────────────────────────────────────────
  a("design-ux", "UX Designer", "design", "ux", "User experience design, information architecture, and usability principles.", M.GENERAL_GEMMA26, ["ux", "information-architecture", "usability", "wireframes", "flows"], 9),
  a("design-ui", "UI Designer", "design", "ui", "Visual interface design, component libraries, and design system creation.", M.GENERAL_GEMMA26, ["ui", "visual-design", "components", "design-system", "figma"], 9),
  a("design-accessibility", "Accessibility (A11y) Designer", "design", "a11y", "WCAG compliance, accessible component design, and inclusive design patterns.", M.GENERAL_GEMMA31, ["accessibility", "wcag", "aria", "inclusive-design", "contrast"], 8),
  a("design-typography", "Typography Specialist", "design", "typography", "Type pairing, hierarchy, readability, and variable font usage.", M.GENERAL_GEMMA31, ["typography", "type-pairing", "hierarchy", "variable-fonts", "readability"], 7),
  a("design-color", "Color System Designer", "design", "color", "Color palette creation, semantic color tokens, dark mode design, and brand colors.", M.GENERAL_GEMMA26, ["color", "palettes", "tokens", "dark-mode", "accessibility"], 8),
  a("design-animation", "Motion & Animation Designer", "design", "motion", "UI animations, micro-interactions, transitions, and motion design principles.", M.GENERAL_GEMMA26, ["animation", "motion", "micro-interactions", "transitions", "framer-motion"], 8),
  a("design-design-system", "Design System Architect", "design", "systems", "Component library design, design tokens, versioning, and documentation.", M.GENERAL_GEMMA31, ["design-system", "tokens", "components", "documentation", "versioning"], 8),
  a("design-responsive", "Responsive Design Specialist", "design", "responsive", "Mobile-first responsive layouts, breakpoints, and fluid typography.", M.CODER_LARGE, ["responsive", "mobile-first", "breakpoints", "fluid", "grid"], 8),
  a("design-icon-system", "Icon System Designer", "design", "icons", "Icon set design, SVG optimization, sizing systems, and icon usage guidelines.", M.GENERAL_GEMMA26, ["icons", "svg", "sizing", "guidelines", "optimization"], 6),
  a("design-data-viz-design", "Data Visualization Designer", "design", "dataviz", "Chart design, graph aesthetics, and data visualization accessibility.", M.GENERAL_GEMMA31, ["data-viz-design", "charts", "graphs", "accessibility", "clarity"], 8),
  a("design-landing-page", "Landing Page Designer", "design", "web", "High-converting landing page design with sections, CTAs, and visual hierarchy.", M.GENERAL_GEMMA26, ["landing-page", "conversion", "cta", "visual-hierarchy", "sections"], 8),
  a("design-mobile-ui", "Mobile UI Designer", "design", "mobile", "iOS and Android UI patterns, gesture design, and native component usage.", M.GENERAL_GEMMA26, ["mobile-ui", "ios", "android", "gestures", "native-components"], 8),
  a("design-dashboard-ui", "Dashboard UI Designer", "design", "dashboard", "Data-dense dashboard layouts, widget design, and information hierarchy.", M.GENERAL_GEMMA31, ["dashboard", "widgets", "density", "hierarchy", "data-display"], 8),
  a("design-email-template", "Email Template Designer", "design", "email", "Responsive email HTML templates, rendering compatibility, and email design patterns.", M.CODER_MEDIUM, ["email-design", "html-email", "responsive", "compatibility", "templates"], 7),
  a("design-brand", "Brand Identity Designer", "design", "branding", "Logo concepts, brand mark guidelines, and visual identity systems.", M.CREATIVE, ["branding", "identity", "logo", "guidelines", "visual-system"], 7),
  a("design-onboarding-flow", "Onboarding Flow Designer", "design", "flows", "User onboarding experience design with progressive disclosure and activation flows.", M.GENERAL_GEMMA26, ["onboarding", "progressive-disclosure", "activation", "flows", "ux"], 7),
  a("design-3d-ui", "3D & Spatial UI Designer", "design", "3d", "WebGL-based 3D interfaces, Three.js components, and spatial design patterns.", M.GENERAL_GEMMA26, ["3d", "threejs", "webgl", "spatial", "immersive"], 6),
  a("design-print", "Print & Document Designer", "design", "print", "PDF templates, report layouts, and print-ready document design.", M.GENERAL_GEMMA31, ["print", "pdf", "reports", "layouts", "typography"], 6),
  a("design-game-ui", "Game UI Designer", "design", "gaming", "HUD design, game menus, and game interface patterns for browser games.", M.CREATIVE, ["game-ui", "hud", "menus", "game-design", "interfaces"], 6),
  a("design-dark-mode", "Dark Mode Specialist", "design", "theming", "Dark mode color systems, elevation, contrast, and theme-switching implementation.", M.GENERAL_GEMMA31, ["dark-mode", "theming", "elevation", "contrast", "switching"], 7),

  // ── PLANNING DOMAIN (25 agents) ──────────────────────────────────────────
  a("plan-architect", "Software Architect", "planning", "architecture", "System architecture design, technology stack selection, and architectural decision records.", M.GENERAL_ULTRA, ["architecture", "adr", "tech-stack", "patterns", "trade-offs"], 9),
  a("plan-project", "Project Manager", "planning", "project-management", "Project planning, WBS, timeline estimation, and risk management.", M.GENERAL_SUPER, ["project-management", "wbs", "timeline", "risks", "milestones"], 9),
  a("plan-sprint", "Agile Sprint Planner", "planning", "agile", "Sprint planning, backlog grooming, story point estimation, and velocity tracking.", M.GENERAL_LLAMA, ["agile", "sprint", "backlog", "story-points", "velocity"], 8),
  a("plan-requirements", "Requirements Analyst", "planning", "requirements", "Business requirements elicitation, functional/non-functional requirements, and acceptance criteria.", M.REASONING_LARGE, ["requirements", "functional", "non-functional", "acceptance-criteria", "brd"], 9),
  a("plan-roadmap", "Product Roadmap Planner", "planning", "product", "Strategic product roadmaps, prioritization frameworks, and quarterly planning.", M.GENERAL_SUPER, ["roadmap", "prioritization", "quarterly", "strategy", "ot-framework"], 8),
  a("plan-risk", "Risk Analyst", "planning", "risk", "Risk identification, risk matrix creation, impact/probability assessment, and mitigation planning.", M.REASONING_LARGE, ["risk-analysis", "risk-matrix", "mitigation", "probability", "impact"], 8),
  a("plan-dependency", "Dependency Mapper", "planning", "dependencies", "System dependency mapping, critical path analysis, and dependency risk assessment.", M.REASONING_NANO, ["dependencies", "critical-path", "mapping", "risks", "sequencing"], 7),
  a("plan-estimation", "Effort Estimation Expert", "planning", "estimation", "Development effort estimation using PERT, story points, and t-shirt sizing.", M.GENERAL_LLAMA, ["estimation", "pert", "story-points", "t-shirt-sizing", "velocity"], 7),
  a("plan-okr", "OKR Framework Planner", "planning", "strategy", "OKR design, key result definition, and measurement framework development.", M.GENERAL_SUPER, ["okrs", "key-results", "measurement", "strategy", "alignment"], 8),
  a("plan-mvp", "MVP Planner", "planning", "product", "MVP scope definition, feature prioritization, and build-measure-learn cycle planning.", M.REASONING_LARGE, ["mvp", "scope", "prioritization", "build-measure-learn", "validation"], 9),
  a("plan-scalability", "Scalability Planner", "planning", "scaling", "Scalability assessment, growth planning, and capacity roadmap for systems.", M.GENERAL_SUPER, ["scalability", "capacity", "growth", "performance", "planning"], 8),
  a("plan-migration", "Migration Planner", "planning", "migration", "System migration strategy, cutover planning, rollback procedures, and data migration.", M.REASONING_LARGE, ["migration", "cutover", "rollback", "data-migration", "strategy"], 8),
  a("plan-integration", "Integration Architecture Planner", "planning", "integration", "Integration patterns, API strategy, ESB design, and service catalog planning.", M.GENERAL_SUPER, ["integration", "api-strategy", "esb", "patterns", "service-catalog"], 7),
  a("plan-data-arch", "Data Architecture Planner", "planning", "data", "Data platform strategy, lake/warehouse design, and governance framework.", M.GENERAL_ULTRA, ["data-architecture", "data-lake", "warehouse", "governance", "strategy"], 8),
  a("plan-capacity", "Capacity Planning Analyst", "planning", "operations", "Infrastructure capacity planning, resource forecasting, and headroom analysis.", M.GENERAL_SUPER, ["capacity", "forecasting", "resources", "headroom", "planning"], 7),
  a("plan-team", "Team Structure Designer", "planning", "organization", "Engineering team structure, Dunbar number, Conway's Law, and org design.", M.GENERAL_LLAMA, ["team-structure", "conways-law", "org-design", "scaling", "communication"], 7),
  a("plan-discovery", "Product Discovery Facilitator", "planning", "product", "Problem framing, opportunity sizing, solution hypothesis, and discovery sprint design.", M.REASONING_LARGE, ["discovery", "problem-framing", "hypothesis", "opportunity", "design-thinking"], 8),
  a("plan-api-strategy", "API Strategy Planner", "planning", "api", "API product strategy, versioning roadmap, developer portal, and monetization.", M.GENERAL_SUPER, ["api-strategy", "versioning", "developer-portal", "monetization", "governance"], 7),
  a("plan-security-roadmap", "Security Roadmap Planner", "planning", "security", "Security maturity assessment, CISO roadmap, and security investment prioritization.", M.GENERAL_ULTRA, ["security-roadmap", "maturity", "ciso", "investments", "priorities"], 7),
  a("plan-budget", "Technology Budget Planner", "planning", "finance", "Tech budget allocation, ROI calculation, build-vs-buy analysis, and cost projection.", M.REASONING_LARGE, ["budget", "roi", "build-vs-buy", "cost-projection", "allocation"], 7),
  a("plan-post-mortem", "Post-Mortem Facilitator", "planning", "incidents", "Structured post-mortem analysis, root cause investigation, and action item planning.", M.GENERAL_LLAMA, ["post-mortem", "root-cause", "blameless", "action-items", "learning"], 7),
  a("plan-technical-debt", "Technical Debt Manager", "planning", "debt", "Technical debt inventory, prioritization, and paydown strategy planning.", M.REASONING_LARGE, ["technical-debt", "inventory", "prioritization", "paydown", "refactoring"], 8),
  a("plan-platform", "Platform Engineering Planner", "planning", "platform", "Internal developer platform design, golden paths, and self-service infrastructure.", M.GENERAL_ULTRA, ["platform-engineering", "idp", "golden-paths", "self-service", "developer-experience"], 8),
  a("plan-open-source", "Open Source Strategy Planner", "planning", "open-source", "OSS strategy, contribution guidelines, governance model, and community building.", M.GENERAL_LLAMA, ["open-source", "governance", "contribution", "community", "license"], 6),
  a("plan-compliance-roadmap", "Compliance Roadmap Planner", "planning", "compliance", "SOC2, ISO27001, and GDPR compliance roadmap planning and gap analysis.", M.GENERAL_SUPER, ["compliance-roadmap", "soc2", "iso27001", "gdpr", "gaps"], 7),

  // ── TESTING DOMAIN (20 agents) ───────────────────────────────────────────
  a("test-unit", "Unit Test Writer", "testing", "unit", "Writes comprehensive unit tests with edge cases and mocking strategies.", M.CODER_LARGE, ["unit-testing", "jest", "vitest", "mocking", "edge-cases"], 9),
  a("test-integration", "Integration Test Designer", "testing", "integration", "Integration test strategies, API testing, and database integration tests.", M.CODER_MEDIUM, ["integration-testing", "supertest", "api-testing", "database", "contracts"], 8),
  a("test-e2e", "E2E Test Engineer", "testing", "e2e", "End-to-end test suites with Playwright, Cypress, and test automation frameworks.", M.CODER_LARGE, ["e2e", "playwright", "cypress", "automation", "selectors"], 8),
  a("test-performance", "Performance Test Engineer", "testing", "performance", "Load testing, stress testing, and performance benchmarking with k6, JMeter.", M.CODER_POOLSIDE_M, ["load-testing", "k6", "jmeter", "stress-testing", "benchmarks"], 8),
  a("test-api", "API Contract Tester", "testing", "api", "API contract testing, Pact tests, and consumer-driven contract testing.", M.CODER_MEDIUM, ["api-testing", "pact", "contracts", "consumer-driven", "openapi"], 8),
  a("test-security-testing", "Security Test Engineer", "testing", "security", "Security test scenarios, DAST testing, and OWASP test case generation.", M.REASONING_LARGE, ["security-testing", "dast", "owasp", "test-cases", "vulnerabilities"], 8),
  a("test-coverage", "Test Coverage Analyst", "testing", "coverage", "Coverage analysis, gap identification, and test strategy improvement recommendations.", M.GENERAL_LLAMA, ["coverage", "gaps", "strategy", "istanbul", "c8"], 7),
  a("test-regression", "Regression Test Planner", "testing", "regression", "Regression test suite design, smoke tests, and release validation strategies.", M.GENERAL_LLAMA, ["regression", "smoke-tests", "validation", "release", "automation"], 7),
  a("test-mobile-testing", "Mobile Test Engineer", "testing", "mobile", "Mobile app testing with Detox, Appium, and device farm strategies.", M.CODER_MEDIUM, ["mobile-testing", "detox", "appium", "device-farm", "emulators"], 7),
  a("test-accessibility-testing", "Accessibility Test Engineer", "testing", "a11y", "Automated A11y testing with axe, manual screen reader testing, and WCAG validation.", M.CODER_MEDIUM, ["a11y-testing", "axe", "screen-readers", "wcag", "keyboard"], 7),
  a("test-chaos", "Chaos Engineering Specialist", "testing", "chaos", "Chaos experiments, failure injection, and resilience testing.", M.GENERAL_SUPER, ["chaos-engineering", "failure-injection", "resilience", "netflix-chaos", "game-days"], 7),
  a("test-visual", "Visual Regression Tester", "testing", "visual", "Visual regression testing with Percy, Chromatic, and snapshot comparisons.", M.CODER_LARGE, ["visual-regression", "percy", "chromatic", "snapshots", "storybook"], 7),
  a("test-data-validation", "Data Validation Tester", "testing", "data", "Data quality tests, schema validation, and data pipeline test strategies.", M.CODER_MEDIUM, ["data-validation", "schema", "great-expectations", "data-quality", "assertions"], 7),
  a("test-tdd-coach", "TDD Coach", "testing", "methodology", "Test-driven development guidance, red-green-refactor cycles, and TDD best practices.", M.REASONING_LARGE, ["tdd", "red-green-refactor", "methodology", "feedback-loop", "design"], 7),
  a("test-bdd", "BDD Scenario Writer", "testing", "bdd", "Cucumber feature files, Gherkin scenarios, and behaviour-driven test design.", M.GENERAL_LLAMA, ["bdd", "cucumber", "gherkin", "scenarios", "behaviour-driven"], 7),
  a("test-flaky", "Flaky Test Debugger", "testing", "debugging", "Identifies and fixes flaky tests, race conditions, and non-deterministic test behavior.", M.REASONING_LARGE, ["flaky-tests", "race-conditions", "debugging", "determinism", "reliability"], 7),
  a("test-benchmark", "Micro-Benchmark Engineer", "testing", "performance", "Micro-benchmark design with Criterion, Benchmark.js, and performance profiling.", M.CODER_POOLSIDE_M, ["micro-benchmarks", "criterion", "profiling", "performance", "baselines"], 7),
  a("test-fuzzing", "Fuzzing Engineer", "testing", "security", "Fuzz testing setup, corpus management, and coverage-guided fuzzing strategies.", M.CODER_POOLSIDE_M, ["fuzzing", "corpus", "coverage-guided", "libfuzzer", "afl"], 7),
  a("test-database-testing", "Database Test Engineer", "testing", "database", "Database migration testing, stored procedure testing, and data integrity validation.", M.CODER_MEDIUM, ["db-testing", "migrations", "integrity", "transactions", "rollback"], 7),
  a("test-cicd-testing", "CI/CD Test Optimizer", "testing", "cicd", "Parallelizing tests, test sharding, caching strategies, and CI performance optimization.", M.CODER_POOLSIDE_M, ["ci-testing", "parallelization", "sharding", "caching", "optimization"], 7),

  // ── BUSINESS DOMAIN (20 agents) ──────────────────────────────────────────
  a("biz-strategy", "Business Strategist", "business", "strategy", "Strategic planning, competitive positioning, and growth strategy development.", M.GENERAL_ULTRA, ["strategy", "positioning", "growth", "competitive", "frameworks"], 9),
  a("biz-finance", "Financial Modeler", "business", "finance", "Financial modeling, P&L projections, DCF valuation, and unit economics.", M.REASONING_LARGE, ["financial-modeling", "dcf", "unit-economics", "projections", "valuation"], 8),
  a("biz-legal", "Legal Document Reviewer", "business", "legal", "Contract review, legal risk assessment, and clause analysis.", M.GENERAL_ULTRA, ["legal", "contracts", "risks", "clauses", "compliance"], 7),
  a("biz-hr", "HR Policy Advisor", "business", "hr", "HR policy design, job description creation, and performance review frameworks.", M.GENERAL_LLAMA, ["hr", "policies", "job-descriptions", "performance", "culture"], 7),
  a("biz-product-manager", "Product Manager", "business", "product", "Product strategy, feature prioritization, go-to-market, and metrics definition.", M.REASONING_LARGE, ["product-management", "prioritization", "go-to-market", "metrics", "strategy"], 9),
  a("biz-growth", "Growth Hacker", "business", "growth", "Growth loops, viral coefficients, and user acquisition strategy.", M.CREATIVE, ["growth", "viral-loops", "acquisition", "retention", "experimentation"], 8),
  a("biz-pricing", "Pricing Strategist", "business", "pricing", "Pricing model design, value-based pricing, and competitive pricing strategy.", M.REASONING_LARGE, ["pricing", "value-based", "competitive", "models", "elasticity"], 8),
  a("biz-market-entry", "Market Entry Strategist", "business", "strategy", "Market entry analysis, localization strategy, and international expansion planning.", M.GENERAL_SUPER, ["market-entry", "localization", "international", "expansion", "strategy"], 7),
  a("biz-ops", "Business Operations Analyst", "business", "operations", "Process documentation, operational efficiency, and workflow optimization.", M.GENERAL_LLAMA, ["operations", "processes", "efficiency", "workflows", "documentation"], 7),
  a("biz-fundraising", "Fundraising Advisor", "business", "funding", "Fundraising strategy, investor narrative, and term sheet analysis.", M.REASONING_LARGE, ["fundraising", "investors", "narrative", "term-sheet", "valuation"], 8),
  a("biz-partnership", "Partnership Development Manager", "business", "partnerships", "Partnership identification, deal structure, and co-marketing strategy.", M.GENERAL_LLAMA, ["partnerships", "deals", "co-marketing", "ecosystem", "alliances"], 7),
  a("biz-customer-success", "Customer Success Manager", "business", "customer-success", "Customer health scoring, churn prevention, and expansion playbooks.", M.GENERAL_LLAMA, ["customer-success", "health-scoring", "churn", "expansion", "playbooks"], 7),
  a("biz-support", "Customer Support Strategist", "business", "support", "Support ticket categorization, FAQ creation, and self-service strategy.", M.GENERAL_LLAMA, ["support", "tickets", "faq", "self-service", "knowledge-base"], 7),
  a("biz-compliance-biz", "Business Compliance Manager", "business", "compliance", "Regulatory compliance planning, audit preparation, and policy documentation.", M.GENERAL_SUPER, ["compliance", "regulatory", "audit", "policies", "documentation"], 7),
  a("biz-investor-relations", "Investor Relations Advisor", "business", "ir", "Investor communications, board decks, and financial narrative crafting.", M.GENERAL_SUPER, ["investor-relations", "board-deck", "communications", "narrative", "reporting"], 7),
  a("biz-analytics", "Business Analytics Manager", "business", "analytics", "Business KPI design, executive dashboards, and data-driven decision frameworks.", M.REASONING_LARGE, ["business-analytics", "kpis", "dashboards", "decisions", "metrics"], 8),
  a("biz-supply-chain-biz", "Supply Chain Manager", "business", "supply-chain", "Supplier management, procurement strategy, and supply chain risk.", M.GENERAL_LLAMA, ["supply-chain", "suppliers", "procurement", "risk", "logistics"], 6),
  a("biz-esg", "ESG & Sustainability Advisor", "business", "sustainability", "ESG reporting, sustainability strategy, and impact measurement.", M.GENERAL_SUPER, ["esg", "sustainability", "reporting", "impact", "carbon"], 6),
  a("biz-saas-metrics", "SaaS Metrics Analyst", "business", "saas", "ARR, MRR, churn, LTV, CAC, NRR, and SaaS financial health analysis.", M.REASONING_LARGE, ["saas", "arr", "mrr", "ltv", "cac"], 8),
  a("biz-brand-strategy", "Brand Strategist", "business", "branding", "Brand architecture, positioning statement, and brand differentiation strategy.", M.GENERAL_SUPER, ["brand-strategy", "architecture", "positioning", "differentiation", "personality"], 7),

  // ── VOICE/AUDIO DOMAIN (10 agents) ──────────────────────────────────────
  a("voice-script", "Voice Script Writer", "voice", "scripting", "Writes conversational scripts for IVR, voice assistants, and chatbots.", M.CREATIVE, ["voice-scripts", "ivr", "conversational", "tone", "clarity"], 8),
  a("voice-ssml", "SSML Generator", "voice", "tts", "Creates SSML markup for text-to-speech with prosody, breaks, and emphasis.", M.CODER_MEDIUM, ["ssml", "tts", "prosody", "speech-synthesis", "amazon-polly"], 7),
  a("voice-podcast-outline", "Podcast Outline Creator", "voice", "podcasting", "Podcast episode structures, talking points, and guest interview guides.", M.CREATIVE, ["podcast", "outline", "interview-guide", "talking-points", "episodes"], 7),
  a("voice-transcript-analyzer", "Transcript Analyzer", "voice", "analysis", "Audio/video transcript analysis, key moment extraction, and summary generation.", M.GENERAL_QWEN, ["transcripts", "analysis", "key-moments", "summaries", "insights"], 7),
  a("voice-ui-designer", "Voice UI Designer", "voice", "design", "Conversational interface design, dialog flows, and multi-turn conversation modeling.", M.GENERAL_GEMMA26, ["voice-ui", "dialog-flows", "conversation", "intents", "entities"], 7),
  a("voice-accessibility", "Audio Accessibility Specialist", "voice", "accessibility", "Audio descriptions, screen reader optimization, and voice navigation design.", M.GENERAL_GEMMA31, ["audio-accessibility", "descriptions", "screen-reader", "voice-nav", "captions"], 7),
  a("voice-branding", "Voice Brand Designer", "voice", "branding", "Brand voice personality, speech patterns, and voice persona development.", M.CREATIVE, ["voice-brand", "persona", "speech-patterns", "brand-voice", "personality"], 6),
  a("voice-localization", "Voice Localization Specialist", "voice", "localization", "Voice content localization, dialect considerations, and cultural adaptation.", M.GENERAL_LLAMA, ["voice-localization", "dialects", "cultural-adaptation", "translation", "regional"], 6),
  a("voice-audio-product", "Audio Product Manager", "voice", "product", "Audio product strategy, voice feature roadmap, and audio UX metrics.", M.GENERAL_LLAMA, ["audio-product", "voice-features", "roadmap", "metrics", "strategy"], 6),
  a("voice-training-data", "Voice Training Data Curator", "voice", "data", "Voice training dataset curation, speaker diversity, and audio quality standards.", M.GENERAL_QWEN, ["voice-data", "training", "diversity", "quality", "annotation"], 6),

  // ── VIDEO DOMAIN (10 agents) ─────────────────────────────────────────────
  a("video-script", "Video Script Writer", "video", "scripting", "YouTube, course, and explainer video scripts with hooks, pacing, and CTAs.", M.CREATIVE, ["video-scripts", "youtube", "hooks", "pacing", "cta"], 8),
  a("video-storyboard", "Storyboard Creator", "video", "production", "Shot-by-shot storyboard descriptions, camera angles, and visual narrative planning.", M.GENERAL_GEMMA26, ["storyboard", "shots", "camera-angles", "visual-narrative", "production"], 7),
  a("video-captions", "Caption & Subtitle Writer", "video", "accessibility", "Accurate captions, subtitle timing, and multilingual subtitle creation.", M.GENERAL_NANO30, ["captions", "subtitles", "timing", "accessibility", "multilingual"], 7),
  a("video-seo", "Video SEO Optimizer", "video", "seo", "YouTube SEO, titles, descriptions, tags, and thumbnail concepts.", M.GENERAL_LLAMA, ["video-seo", "youtube", "titles", "descriptions", "thumbnails"], 7),
  a("video-course", "Online Course Designer", "video", "education", "Course curriculum design, lesson structure, and learning objective definition.", M.GENERAL_SUPER, ["course-design", "curriculum", "lessons", "objectives", "learning"], 7),
  a("video-short-form", "Short-Form Video Strategist", "video", "social", "TikTok, Reels, and Shorts strategy, hooks, and viral content patterns.", M.CREATIVE, ["short-form", "tiktok", "reels", "shorts", "viral"], 7),
  a("video-animation-brief", "Animation Brief Writer", "video", "animation", "Motion graphics briefs, animation style guides, and explainer video scripts.", M.GENERAL_GEMMA26, ["animation", "motion-graphics", "explainer", "style-guide", "briefs"], 6),
  a("video-testimonial", "Testimonial Video Planner", "video", "marketing", "Customer testimonial video scripts, question guides, and editing notes.", M.CREATIVE, ["testimonials", "customer-stories", "scripts", "editing", "authenticity"], 6),
  a("video-product-demo", "Product Demo Video Planner", "video", "product", "Product demonstration scripts, feature highlight sequences, and demo flow design.", M.GENERAL_LLAMA, ["product-demo", "features", "flow", "scripts", "walkthrough"], 7),
  a("video-live-stream", "Live Stream Planner", "video", "live", "Live stream structure, real-time engagement tactics, and production checklists.", M.CREATIVE, ["live-streaming", "engagement", "structure", "production", "checklist"], 6),

  // ── TRADING DOMAIN (50 agents) ───────────────────────────────────────────────
  a("trading-quant-architect", "Quantitative Strategy Architect", "trading", "quant", "Designs complete, production-ready quantitative trading algorithms with rigorous mathematical foundations.", M.REASONING_LARGE, ["quant-strategy", "algorithm-design", "mathematical-models", "backtesting", "alpha-generation"], 10),
  a("trading-orderbook-analyst", "Order Book Microstructure Analyst", "trading", "microstructure", "Expert in L2/L3 order book dynamics, bid-ask spread patterns, and market microstructure anomalies.", M.REASONING_LARGE, ["order-book", "microstructure", "bid-ask", "market-impact", "liquidity"], 10),
  a("trading-spib-dev", "SPIB Model Developer", "trading", "spib", "Implements State Predictive Information Bottleneck models that compress historical market states while preserving maximum predictive power.", M.REASONING_LARGE, ["spib", "information-bottleneck", "latent-representation", "predictive-models", "pytorch"], 10),
  a("trading-tkan-engineer", "T-KAN Network Engineer", "trading", "tkan", "Builds Temporal Kolmogorov-Arnold Networks with learnable spline functions for adaptive dead-zone filtering.", M.REASONING_LARGE, ["tkan", "kan", "spline-functions", "temporal-networks", "dead-zone-filtering"], 10),
  a("trading-alpha-researcher", "Alpha Signal Researcher", "trading", "alpha", "Discovers predictive market signals with statistical significance testing and out-of-sample validation.", M.CODER_LARGE, ["alpha-signals", "signal-discovery", "statistical-testing", "factor-research", "regime-detection"], 9),
  a("trading-alpha-decay", "Alpha Decay Analyst", "trading", "alpha", "Measures signal decay over time and implements adaptive mechanisms to preserve edge as markets adapt.", M.REASONING_LARGE, ["alpha-decay", "signal-half-life", "adaptive-models", "regime-change", "market-adaptation"], 9),
  a("trading-stat-arb", "Statistical Arbitrage Developer", "trading", "arbitrage", "Builds pairs trading, cointegration-based, and cross-asset statistical arbitrage strategies.", M.CODER_LARGE, ["stat-arb", "pairs-trading", "cointegration", "mean-reversion", "spread-trading"], 9),
  a("trading-market-maker", "Market Making Engineer", "trading", "market-making", "Designs asymmetric market making algorithms with adverse selection protection and inventory management.", M.REASONING_LARGE, ["market-making", "adverse-selection", "inventory-management", "spread-capture", "mm-algo"], 9),
  a("trading-hft-optimizer", "HFT Latency Optimizer", "trading", "hft", "Reduces execution latency to microsecond thresholds using kernel bypass, FPGA patterns, and lock-free algorithms.", M.CODER_POOLSIDE_M, ["hft", "latency", "kernel-bypass", "lock-free", "fpga"], 9),
  a("trading-risk-quant", "Risk Management Quant", "trading", "risk", "Designs position sizing, VaR models, drawdown limits, and tail-risk hedging frameworks.", M.REASONING_LARGE, ["risk-management", "var", "position-sizing", "drawdown", "tail-risk"], 9),
  a("trading-vol-surface", "Volatility Surface Modeler", "trading", "derivatives", "Constructs and calibrates IV surfaces using SVI, SABR, and local-vol models.", M.REASONING_LARGE, ["volatility-surface", "iv-surface", "sabr", "svi", "local-vol"], 8),
  a("trading-options-dev", "Options Strategy Developer", "trading", "derivatives", "Builds options pricing models, delta-hedging systems, and multi-leg options strategies.", M.REASONING_LARGE, ["options", "black-scholes", "delta-hedging", "greeks", "multi-leg"], 8),
  a("trading-crypto-analyst", "Crypto Market Analyst", "trading", "crypto", "Specialist in crypto-specific patterns: funding rates, liquidation cascades, on-chain flows, whale behavior.", M.CODER_LARGE, ["crypto", "funding-rates", "liquidations", "on-chain", "whale-tracking"], 9),
  a("trading-defi-analyst", "DeFi Protocol Analyst", "trading", "defi", "Analyzes AMM mechanics, yield opportunities, MEV, and cross-chain arbitrage in DeFi protocols.", M.REASONING_LARGE, ["defi", "amm", "mev", "yield-farming", "cross-chain-arb"], 8),
  a("trading-momentum-dev", "Momentum Strategy Developer", "trading", "momentum", "Builds trend-following systems with adaptive lookback periods and regime-conditional entry filters.", M.CODER_LARGE, ["momentum", "trend-following", "breakout", "adaptive-lookback", "regime-filter"], 9),
  a("trading-mean-rev", "Mean Reversion Strategist", "trading", "mean-reversion", "Designs mean-reversion strategies using Ornstein-Uhlenbeck processes, z-score entry, and half-life estimation.", M.CODER_LARGE, ["mean-reversion", "ou-process", "z-score", "half-life", "cointegration"], 9),
  a("trading-cross-asset", "Cross-Asset Correlation Analyst", "trading", "macro", "Models inter-market dynamics, correlation regime shifts, and macro factor exposures.", M.REASONING_LARGE, ["cross-asset", "correlations", "macro-factors", "regime-shift", "risk-parity"], 8),
  a("trading-ml-features", "ML Feature Engineer (Finance)", "trading", "ml", "Builds financial ML feature pipelines: tick aggregation, order flow imbalance, VWAP deviation, microstructure features.", M.CODER_LARGE, ["ml-features", "feature-engineering", "tick-data", "order-flow-imbalance", "vwap"], 9),
  a("trading-backtest-dev", "Backtesting Framework Developer", "trading", "backtest", "Builds vectorized and event-driven backtesting frameworks with realistic slippage, fees, and market impact modeling.", M.CODER_LARGE, ["backtesting", "vectorized-backtest", "event-driven", "slippage", "market-impact"], 9),
  a("trading-exec-algo", "Execution Algorithm Designer", "trading", "execution", "Designs TWAP, VWAP, IS, and adaptive execution algorithms to minimize market impact.", M.CODER_POOLSIDE_M, ["execution", "twap", "vwap", "implementation-shortfall", "smart-order-routing"], 8),
  a("trading-order-flow", "Order Flow Analyst", "trading", "microstructure", "Reads tape, reconstructs order flow, and identifies informed vs. uninformed trading via PIN models.", M.REASONING_LARGE, ["order-flow", "tape-reading", "informed-trading", "pin-model", "toxicity"], 8),
  a("trading-funding-arb", "Funding Rate Arbitrageur", "trading", "crypto", "Builds systematic strategies exploiting perpetual futures funding rate mispricings across exchanges.", M.CODER_LARGE, ["funding-arbitrage", "perpetuals", "basis-trading", "cross-exchange", "funding-rate"], 9),
  a("trading-liquidation", "Liquidation Cascade Predictor", "trading", "crypto", "Models liquidation cascade risk from leverage concentration, identifying high-probability cascade zones.", M.REASONING_LARGE, ["liquidations", "cascade-risk", "leverage-map", "open-interest", "liquidation-levels"], 8),
  a("trading-ohlcv-pattern", "OHLCV Pattern Researcher", "trading", "technical", "Systematically tests candlestick patterns, chart formations, and price action setups for statistical edge.", M.CODER_LARGE, ["candlestick-patterns", "chart-patterns", "technical-analysis", "price-action", "statistical-edge"], 7),
  a("trading-regime-class", "Market Regime Classifier", "trading", "regime", "Builds HMM and change-point detection models to classify bull/bear/ranging regimes and switch strategies.", M.REASONING_LARGE, ["regime-classification", "hmm", "change-point-detection", "regime-switch", "adaptive-strategy"], 9),
  a("trading-sentiment-nlp", "Market Sentiment NLP Analyst", "trading", "nlp", "Processes news, social media, and earnings calls for sentiment signals with NLP models.", M.GENERAL_LLAMA, ["sentiment-analysis", "news-nlp", "social-media", "earnings-nlp", "alternative-data"], 7),
  a("trading-crypto-perp", "Perpetual Futures Specialist", "trading", "derivatives", "Expert in perp funding mechanics, basis curves, and carry trade construction on crypto exchanges.", M.CODER_LARGE, ["perpetuals", "funding", "basis", "carry-trade", "derivatives"], 8),
  a("trading-portfolio-opt", "Portfolio Optimization Quant", "trading", "portfolio", "Applies mean-variance, Black-Litterman, and hierarchical risk parity to multi-strategy portfolios.", M.REASONING_LARGE, ["portfolio-optimization", "mean-variance", "black-litterman", "hrp", "allocation"], 8),
  a("trading-factor-model", "Factor Model Researcher", "trading", "factors", "Builds multi-factor equity models using momentum, value, quality, low-vol, and alternative factors.", M.REASONING_LARGE, ["factor-models", "momentum-factor", "value-factor", "quality-factor", "barra"], 8),
  a("trading-python-impl", "Trading Python Implementer", "trading", "implementation", "Translates quant research into production Python code with pandas, numpy, ccxt, and vectorbt.", M.CODER_LARGE, ["python", "pandas", "numpy", "ccxt", "vectorbt"], 9),
  a("trading-data-pipeline", "Financial Data Pipeline Engineer", "trading", "data", "Builds low-latency data pipelines for tick, OHLCV, orderbook, and alternative data sources.", M.CODER_MEDIUM, ["data-pipeline", "tick-data", "ohlcv", "websocket", "kafka"], 8),
  a("trading-exchange-api", "Exchange API Integrator", "trading", "integration", "Integrates with Binance, Bybit, OKX, and Coinbase Advanced APIs for order placement and data.", M.CODER_MEDIUM, ["exchange-api", "binance", "bybit", "okx", "ccxt"], 8),
  a("trading-performance-attr", "Performance Attribution Analyst", "trading", "analytics", "Decomposes strategy P&L into alpha, beta, factor, and execution contributions.", M.REASONING_LARGE, ["performance-attribution", "pnl-decomposition", "alpha-beta", "factor-attribution", "execution-cost"], 7),
  a("trading-monte-carlo", "Monte Carlo Simulation Expert", "trading", "simulation", "Runs Monte Carlo simulations for strategy robustness testing under different market scenarios.", M.CODER_LARGE, ["monte-carlo", "simulation", "stress-testing", "scenario-analysis", "robustness"], 8),
  a("trading-ml-model", "Trading ML Model Developer", "trading", "ml", "Builds gradient boosting, LSTM, and transformer models for price prediction and signal generation.", M.CODER_LARGE, ["lstm", "gradient-boosting", "xgboost", "lightgbm", "pytorch"], 9),
  a("trading-reinforcement", "RL Trading Agent Developer", "trading", "rl", "Builds reinforcement learning trading agents using PPO, SAC, and TD3 for continuous action spaces.", M.CODER_LARGE, ["reinforcement-learning", "ppo", "sac", "td3", "trading-env"], 8),
  a("trading-graph-neural", "Graph Neural Network Analyst", "trading", "ml", "Applies GNNs to model cross-asset relationships and systemic risk propagation.", M.REASONING_LARGE, ["gnn", "graph-neural-network", "cross-asset", "systemic-risk", "relational-modeling"], 7),
  a("trading-alt-data", "Alternative Data Specialist", "trading", "alt-data", "Sources and processes satellite imagery, credit card data, app downloads, and other alt-data for alpha.", M.CODER_LARGE, ["alt-data", "satellite", "credit-card-data", "app-downloads", "web-scraping"], 7),
  a("trading-crypto-onchain", "On-Chain Analytics Expert", "trading", "crypto", "Analyzes blockchain data: whale wallets, exchange flows, staking, and network metrics for trading signals.", M.REASONING_LARGE, ["on-chain", "blockchain-analytics", "whale-wallets", "exchange-flows", "glassnode"], 8),
  a("trading-yield-curve", "Yield Curve Strategist", "trading", "fixed-income", "Models yield curve dynamics, term structure, and curve flattening/steepening trades.", M.REASONING_LARGE, ["yield-curve", "term-structure", "duration", "convexity", "curve-trades"], 7),
  a("trading-fx-specialist", "FX Market Specialist", "trading", "fx", "Builds systematic FX strategies exploiting carry, momentum, and purchasing-power-parity deviations.", M.CODER_LARGE, ["fx", "carry-trade", "ppp", "fx-momentum", "currency-pairs"], 7),
  a("trading-hft-mm", "HFT Market Maker", "trading", "hft", "Designs ultra-low-latency market making with adverse selection avoidance and optimal inventory management.", M.CODER_POOLSIDE_M, ["hft-mm", "latency-arbitrage", "adverse-selection", "inventory-skew", "queue-priority"], 9),
  a("trading-paper-validator", "Paper Trading Validator", "trading", "validation", "Validates strategies in paper trading environments, comparing simulation vs. live execution quality.", M.CODER_MEDIUM, ["paper-trading", "validation", "slippage-measurement", "execution-quality", "simulation"], 8),
  a("trading-risk-limits", "Risk Limit Framework Designer", "trading", "risk", "Designs comprehensive risk frameworks with dynamic position limits, drawdown kill switches, and correlation adjustments.", M.REASONING_LARGE, ["risk-limits", "kill-switch", "position-limits", "drawdown-control", "correlation-risk"], 9),
  a("trading-ccxt-dev", "CCXT Library Expert", "trading", "implementation", "Expert in the CCXT unified exchange library for multi-exchange data collection and order routing.", M.CODER_MEDIUM, ["ccxt", "multi-exchange", "order-routing", "unified-api", "exchange-normalization"], 8),
  a("trading-sharpe-optimizer", "Sharpe Ratio Optimizer", "trading", "optimization", "Optimizes strategy parameters specifically for risk-adjusted returns via walk-forward analysis.", M.CODER_LARGE, ["sharpe-optimization", "walk-forward", "parameter-optimization", "overfitting-prevention", "robustness"], 9),
  a("trading-crypto-basis", "Crypto Basis Trader", "trading", "derivatives", "Builds cash-and-carry arbitrage strategies exploiting spot/futures basis across crypto markets.", M.CODER_LARGE, ["basis-trading", "cash-and-carry", "spot-futures", "convergence", "basis-risk"], 8),
  a("trading-systematic", "Systematic CTA Developer", "trading", "cta", "Designs trend-following CTA programs across multiple asset classes with diversification overlays.", M.REASONING_LARGE, ["systematic-cta", "trend-following", "diversification", "multi-asset", "cta-program"], 8),
  a("trading-execution-cost", "Transaction Cost Analyst", "trading", "execution", "Models bid-ask spread costs, market impact, timing risk, and opportunity cost of execution delay.", M.CODER_LARGE, ["tca", "transaction-costs", "market-impact", "timing-risk", "execution-optimization"], 7),

  // ── TITAN KERNEL DOMAIN (20 agents) ──────────────────────────────────────────
  a("titan-kernel-architect", "TITAN Kernel Architect", "titan", "architecture", "Designs the modular C++20 kernel structure for the SwarmAI Agent OS runtime with lock-free primitives.", M.CODER_POOLSIDE_M, ["c++20", "kernel-design", "modular-architecture", "runtime", "system-design"], 10),
  a("titan-lockfree-engineer", "Lock-Free Data Structure Engineer", "titan", "concurrency", "Implements lock-free queues, stacks, hash maps, and ring buffers using C++20 atomics and memory ordering.", M.CODER_POOLSIDE_M, ["lock-free", "atomics", "memory-ordering", "wait-free", "concurrent-data-structures"], 10),
  a("titan-memory-allocator", "Custom Memory Allocator Designer", "titan", "memory", "Builds slab allocators, arena allocators, and pool allocators for zero-fragmentation, low-latency memory management.", M.CODER_POOLSIDE_M, ["memory-allocator", "slab-allocator", "arena-allocator", "jemalloc", "tcmalloc"], 10),
  a("titan-abi-specialist", "Native ABI Binding Specialist", "titan", "abi", "Designs C-compatible ABI entry points for dynamic tool loading with zero-copy buffer passing conventions.", M.CODER_POOLSIDE_M, ["native-abi", "dynamic-loading", "dlopen", "ffi", "c-abi"], 9),
  a("titan-ipc-engineer", "POSIX IPC & Shared Memory Engineer", "titan", "ipc", "Implements shm_open/mmap IPC channels with Cap'n Proto serialization for zero-copy inter-process communication.", M.CODER_POOLSIDE_M, ["posix-ipc", "shared-memory", "mmap", "shm-open", "zero-copy"], 10),
  a("titan-capnproto", "Cap'n Proto Serialization Expert", "titan", "serialization", "Designs Cap'n Proto schemas for zero-copy, zero-parse serialization of tool inputs and outputs.", M.CODER_POOLSIDE_M, ["capnproto", "zero-copy", "serialization", "schemas", "rpc"], 9),
  a("titan-hnsw-impl", "HNSW Vector Index Implementer", "titan", "search", "Implements a high-performance HNSW approximate nearest-neighbor index for the 5,000+ tool semantic router.", M.CODER_POOLSIDE_M, ["hnsw", "ann", "vector-search", "hnswlib", "faiss"], 9),
  a("titan-compiler-validator", "Automated Compiler Validation Engineer", "titan", "testing", "Builds the automated compilation and test harness loop that validates each generated module against Clang.", M.CODER_POOLSIDE_M, ["clang", "cmake", "ctest", "sanitizers", "automated-testing"], 10),
  a("titan-perf-profiler", "Systems Performance Profiler", "titan", "performance", "Profiles kernel modules with perf, vtune, and heaptrack to identify and eliminate latency bottlenecks.", M.CODER_POOLSIDE_M, ["profiling", "perf", "vtune", "heaptrack", "cpu-optimization"], 9),
  a("titan-cmake-builder", "CMake Build System Engineer", "titan", "build", "Designs the CMake/Ninja build system for the modular kernel with precompiled headers, LTO, and PGO.", M.CODER_MEDIUM, ["cmake", "ninja", "lto", "pgo", "build-system"], 8),
  a("titan-concurrency-designer", "C++20 Concurrency Designer", "titan", "concurrency", "Implements coroutines, executors, and async task systems using C++20 coroutines and the Asio library.", M.CODER_POOLSIDE_M, ["c++20-coroutines", "executors", "async", "asio", "task-system"], 9),
  a("titan-sanitizer-engineer", "Memory Safety & Sanitizer Engineer", "titan", "safety", "Integrates AddressSanitizer, ThreadSanitizer, and UBSan into the build pipeline for safety guarantees.", M.CODER_MEDIUM, ["asan", "tsan", "ubsan", "memory-safety", "undefined-behavior"], 8),
  a("titan-linker-specialist", "Dynamic Linker & Module Loading Specialist", "titan", "linking", "Implements hot-reloadable module loading with dlopen/dlsym and atomic pointer swap for zero-downtime updates.", M.CODER_POOLSIDE_M, ["dynamic-linking", "dlopen", "hot-reload", "shared-libraries", "plugin-system"], 9),
  a("titan-simd-optimizer", "SIMD/AVX Optimization Specialist", "titan", "performance", "Vectorizes numerical kernels using AVX-512 and ARM NEON intrinsics for maximum throughput.", M.CODER_POOLSIDE_M, ["simd", "avx-512", "neon", "vectorization", "intrinsics"], 8),
  a("titan-cache-optimizer", "CPU Cache & Memory Hierarchy Optimizer", "titan", "performance", "Optimizes data structures and access patterns for L1/L2/L3 cache locality using data-oriented design.", M.CODER_POOLSIDE_M, ["cache-optimization", "data-oriented-design", "memory-hierarchy", "prefetching", "cache-line"], 9),
  a("titan-network-kernel", "Kernel Bypass Networking Expert", "titan", "networking", "Implements DPDK and io_uring based networking for sub-microsecond latency in the agent communication bus.", M.CODER_POOLSIDE_M, ["dpdk", "io-uring", "kernel-bypass", "zero-copy-networking", "rdma"], 8),
  a("titan-git-committer", "Git Automation & CI Engineer", "titan", "devops", "Designs the automated git commit pipeline that pushes verified kernel modules to GitHub after passing tests.", M.CODER_MEDIUM, ["git-automation", "ci-cd", "libgit2", "gitops", "automated-commits"], 8),
  a("titan-containerization", "Compilation Sandbox Designer", "titan", "security", "Designs the secure, lightweight sandbox environment for compiling and testing untrusted kernel modules.", M.CODER_MEDIUM, ["sandbox", "seccomp", "namespaces", "landlock", "compilation-isolation"], 8),
  a("titan-entropy-gated", "Entropy-Gated Router Developer", "titan", "routing", "Implements the Entropy-Gated Routing (EGR) system that bypasses the Semantic Bus for low-entropy tokens.", M.REASONING_LARGE, ["entropy-gated-routing", "egr", "semantic-bus", "routing-optimization", "token-entropy"], 9),
  a("titan-parl-optimizer", "PARL Reward Optimizer", "titan", "rl", "Implements the Parallel-Agent Reinforcement Learning reward function that optimizes for quality, parallelization ratio, and cost.", M.REASONING_LARGE, ["parl", "reinforcement-learning", "reward-optimization", "parallel-agents", "multi-objective-rl"], 9),
];

export function getAgentsByDomain(domain: string): AgentDefinition[] {
  return AGENT_REGISTRY.filter((a) => a.domain === domain);
}

export function getAgentById(id: string): AgentDefinition | undefined {
  return AGENT_REGISTRY.find((a) => a.id === id);
}

export function searchAgents(query: string): AgentDefinition[] {
  const q = query.toLowerCase();
  return AGENT_REGISTRY.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.domain.includes(q) ||
      a.subdomain.includes(q) ||
      a.capabilities.some((c) => c.includes(q)),
  );
}

export function getAgentsForDomains(domains: string[]): AgentDefinition[] {
  if (!domains || domains.length === 0) return AGENT_REGISTRY;
  return AGENT_REGISTRY.filter((a) => domains.includes(a.domain));
}

export const DOMAINS = [
  "code",
  "research",
  "writing",
  "data",
  "security",
  "devops",
  "aiml",
  "design",
  "planning",
  "testing",
  "business",
  "voice",
  "video",
  "trading",
  "titan",
] as const;